### ISSUE TITLE
Run azure/login@v1 = login failed

### ISSUE THREAD

**Issue by daltskin** [Azure/webapps-deploy#1]
```
 - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
```

Generates: 

Run azure/login@v1
/usr/bin/az --version
WARNING: You have 3 updates available. Consider updating your CLI installation.
azure-cli                         2.0.74 *

command-modules-nspkg              2.0.3
core                              2.0.74 *
nspkg                              3.0.4
telemetry                          1.0.3 *

Python location '/opt/az/bin/python3'
Extensions directory '/home/runner/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Sep 20 2019, 05:42:39) 
[GCC 7.4.0]

Legal docs and information: aka.ms/AzureCliLegal

Login failed. Please check the credentials.
##[error]Error: The process '/usr/bin/az' failed because one or more lines were written to the STDERR stream
##[error]Node run failed with exit code 1

**Comment by daltskin** [comment]
As per: https://github.com/Azure/actions

should be:

```
 - uses: azure/actions/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
```

**Comment by SumiranAgg** [comment]
@daltskin Can you use azure/login@v1 now?

**Comment by daltskin** [comment]
Yes - that now works, thanks for the update.

**Comment by sajeetharan** [comment]
@daltskin I am using azure/login@v1 and getting same error

**Comment by Bulletninja** [comment]
I'm the same situation as @sajeetharan right now.

**Comment by zhenming91** [comment]
Same.. following the tutorial here https://docs.microsoft.com/en-us/azure/container-instances/container-instances-github-action

**Comment by ddynamight** [comment]
> creds: ${{ secrets.AZURE_CREDENTIALS }}

Does any body know what the contents of ${{ secrets.AZURE_CREDENTIALS }} whould be?

As this is not clear.
