### ISSUE TITLE
Error "Failed to change file that is currently being used" when deploying to a .NET 5 site with WebSockets

### ISSUE THREAD

**Issue by ashmind** [Azure/webapps-deploy#100]
I am deploying a zip file to a .NET 5 website, using this configuration:
```
- uses: azure/webapps-deploy@v2
  with:
    app-name: sharplab-edge
    package: WebApp.Server.zip
```

I only added this deployment just now, and I am running into an error:
> Error: Failed to change file that is currently being used "D:\home\site\wwwroot\SharpLab.Runtime.dll"

<details>
<summary>Full log</summary>

```
Run azure/webapps-deploy@v2
  with:
    app-name: sharplab-edge
    package: WebApp.Server.zip
    slot-name: production
  env:
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
Package deployment using ZIP Deploy initiated.
Updating submodules.
Preparing deployment for commit id '7561bb78b5'.
Generating deployment script.
Using cached version of deployment script (command: 'azure -y --no-dot-deployment -r "D:\local\Temp\zipdeploy\extracted" -o "D:\home\site\deployments\tools" --basic --sitePath "D:\local\Temp\zipdeploy\extracted"').
Running deployment command...
Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling Basic Web Site deployment.
Creating app_offline.htm
Error: Failed to change file that is currently being used "D:\home\site\wwwroot\SharpLab.Runtime.dll"
KuduSync.NET from: 'D:\local\Temp\zipdeploy\extracted' to: 'D:\home\site\wwwroot'
Copying file: 'appsettings.Development.json'
Copying file: 'appsettings.json'
Copying file: 'SharpLab.Native.Profiler.dll'
Copying file: 'SharpLab.Native.Profiler.pdb'
Copying file: 'SharpLab.Runtime.dll'
Failed exitCode=1, command="kudusync" -v 50  -f "D:\local\Temp\zipdeploy\extracted" -t "D:\home\site\wwwroot" -n "D:\home\site\deployments\7561bb78b59f41d5a5d59fdf27c09a6e\manifest" -p "D:\home\site\deployments\4be36940f6a4876eed6d36ed24c97117df5433d31609801997951\manifest" -i ".git;.hg;.deployment;deploy.cmd"
An error has occurred during web site deployment.
Error: Failed to change file that is currently being used "D:\home\site\wwwroot\SharpLab.Runtime.dll"\r\nD:\Program Files (x86)\SiteExtensions\Kudu\91.21119.4922\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"
Error: Failed to deploy web package to App Service.
Error: Deployment Failed with Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
Successfully updated deployment History at https://sharplab-edge.scm.azurewebsites.net/api/deployments/29a251b6083275b643acd856dc6d449e86c587821609802731619
App Service Application URL: http://sharplab-edge.azurewebsites.net
```

</details>

I thought this might be due to the site not correctly handling `app_offline.htm` (maybe due to a WebSocket connection). But on the other hand when using SCM I can somehow do anything with the files -- they don't seem locked at all even without app_offline.

Not sure what's the actual problem and the right solution here -- maybe action should have an option to stop/start web app explicitly, or a wait/retry setting? Either way some graceful way of handling this and letting the user know what exactly is wrong would be great.

**Comment by ashmind** [comment]
Interestingly, that even fails if I run `az webapp stop` right before it, probably because stop is not fully processed yet?
Seems like wait/retry would be the best solution here.

**Comment by AmrutaKawade** [comment]
Can you try with run from package deploy option? https://docs.microsoft.com/en-us/azure/app-service/deploy-run-package#enable-running-from-package

I have found similar older issue https://github.com/projectkudu/kudu/issues/2849

**Comment by 20shivangi** [comment]
@ashmind Have you tried with the above option ?

**Comment by 20shivangi** [comment]
@ashmind Any update here ?

**Comment by 20shivangi** [comment]
Since there has been no response, we are closing the issue. Please feel free to reopen in case of any queries. Thanks.
