### ISSUE TITLE
Site Credential changed after web app backup restore? 

### ISSUE THREAD

**Issue by Kapkan-Lesion** [Azure/webapps-deploy#105]
Hi,

(posted this in the Kudu repo's issue list, but thought maybe web app deploy is also a fitting criteria, hence pasting it over)

A rather simple yet strange question.

We know that there's a single set of Site/App Credential which can be used for deployment purposes. userPWD inside the web app's given publish profile can be leveraged to execute deployment operations at commandline.

We use MsBuild CLI with the userPWD inside publishing profile on an Azure web app to deploy our apps to azure. Previously we have assumed that this userPWD is static, in that it will not change regardless of the management operations happening to this web app.

However, just now I did a backup & restore with this web app to test certain scenarios where the userPWD may change. I was under the impression that a restore should not change the publishing profile, but surprisingly enough this was changed.

I did a quick repro with a blank web app, this time, however, restore conserved the original userPWD inside the publishing profile, nothing was touched there.

Was wondering why did this happen? Are there any scenarios where site credential will change without us touching it (or resetting it)?

Thanks!

**Comment by aksm-ms** [comment]
@Kapkan-Lesion Kudu project is the right place for raising this issue. This repo has Azure webapps-deploy Github action code which does not update publish profile.

**Comment by aksm-ms** [comment]
aksm-ms
