### ISSUE TITLE
App service gives "service unavailable 503" after successful deployment

### ISSUE THREAD

**Issue by harshiniks** [Azure/webapps-deploy#109]
We were using webapps-deploy to deploy our .net core 3.0 app to app service on azure and everything worked fine.
Once we bumped up the .net version, the workflow still passes and deployment is successful but the appservice is not starting.

Same code when deployed through AzDevOps works fine.
**Workflow file:**
[deploy.yml.zip](https://github.com/Azure/webapps-deploy/files/5957203/deploy.yml.zip)
**Successful run**: https://github.com/Azure/GitHubApp_Azure_Backend/runs/1746344627?check_suite_focus=true

**Log from run**:
Package deployment using ZIP Deploy initiated.
Deploy logs can be viewed at https://gua-test-service.scm.azurewebsites.net/api/deployments/c3d19357823046a080a4060f34cce957/log
Successfully deployed web package to App Service.
Successfully updated deployment History at https://gua-test-service.scm.azurewebsites.net/api/deployments/24dd94ed53821e896bbf1455ef074bcaf0f7470e1611285454014
App Service Application URL: http://gua-test-service.azurewebsites.net

**Alternate AzDevOps pipeline** we are currently using: https://dev.azure.com/tfspf-rmpf/gua/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=786

**Comment by 20shivangi** [comment]
@harshiniks Please find the [doc](https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-http-502-http-503) for troubleshooting. It will surely help you

**Comment by 20shivangi** [comment]
@harshiniks Any update here ?

**Comment by harshiniks** [comment]
We had tried all of it and none worked..

**Comment by 20shivangi** [comment]
Is this happening every time ?

**Comment by harshiniks** [comment]
yes

**Comment by 20shivangi** [comment]
Will check and get back on this

**Comment by kaverma** [comment]
Hi @harshiniks, wanted to check whether you are still facing this issue.
