### ISSUE TITLE
Duplicate deployment entries in the Portal

### ISSUE THREAD

**Issue by JasonFreeberg** [Azure/webapps-deploy#110]
> https://github.com/projectkudu/kudu/issues/3268

When deploying with this action an extra deployment object is created in the `/deployments` list. This clutters the deployments list, and the deployment logs are stored in this extra object, not in the deployment object from GitHub Actions, so it's hard for users to find the right logs. The expected behavior is to have one deployment object with a commit ID that matches the one in GitHub, and that all the logs are in that object.

## Duplicate entries in Kudu

![image](https://user-images.githubusercontent.com/18747768/108121291-6726e500-7057-11eb-82e6-f37e0db418bd.png)

## ... which creates duplicates in the deployment center

![image](https://user-images.githubusercontent.com/18747768/108121764-29768c00-7058-11eb-8f1d-1a1d38062f14.png)

- It looks like the message is added to every push deployment handler: https://github.com/projectkudu/kudu/blob/13824205c60a4bdb53896b9553ef1f370a93b911/Kudu.Services/Deployment/PushDeploymentController.cs#L34
- This method adds the deployment to the deployments API: https://github.com/projectkudu/kudu/blob/13824205c60a4bdb53896b9553ef1f370a93b911/Kudu.Core/Deployment/ArtifactDeploymentInfo.cs#L8

**Comment by AmrutaKawade** [comment]
We use kudu [zip deploy](https://github.com/projectkudu/kudu/wiki/REST-API#zip-deployment) api for deploying app, which creates first entry in deployments with message `Created via a push deployment`

after this deployment we again update status of deployment here with additional details
https://github.com/Azure/webapps-deploy/blob/b062dd053e72d63cf28324ec55ce8f77ec086947/src/main.ts#L54

which is creating another entry in deployment.

I have fixed this issue by adding additional details while calling zipdeploy itself https://github.com/microsoft/pipelines-appservice-lib/pull/34

and then removing updatestatus call https://github.com/Azure/webapps-deploy/pull/111

**Comment by JasonFreeberg** [comment]
Wow, quick turnaround @AmrutaKawade! Just want to confirm, will the deployment object be tagged with the git commit ID? 

CC @nertim @spellegrino021

**Comment by AmrutaKawade** [comment]
First entry of log will be as is, instead of `Created via a push deployment` message will be json object with sha of commit ID
and second entry will removed

**Comment by spellegrino021** [comment]
> First entry of log will be as is, instead of `Created via a push deployment` message will be json object with sha of commit ID
> and second entry will removed

Hi Amruta, would it be possible for this message to be the corresponding commit message in GitHub? It might make a little more sense to people to have that information rather than the JSON object. Thanks!

**Comment by AmrutaKawade** [comment]
> > First entry of log will be as is, instead of `Created via a push deployment` message will be json object with sha of commit ID
> > and second entry will removed
> 
> Hi @AmrutaKawade would it be possible for this message to be the corresponding commit message in GitHub? It might make a little more sense to people to have that information rather than the JSON object. Thanks!

Hey thanks for suggestion, but unfortunately its not possible.

Currently while running action there are some [environment variables](https://docs.github.com/en/actions/reference/environment-variables) are bydefault available and commit message is not one of them

since Sha is available we can retrieve commit message with [Github API](https://docs.github.com/en/rest/reference/repos#get-a-commit)

and problem with using Github API is [rate-limiting](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting)

Since this api request will be made form Github runner, it will be considered as unauthenticated request which has limit of 60 requests per hour. so if you are using any other actions within your workflow which uses Github apis this limit will exceed immediately. Another approach is take user token as input for action to make authenticated request. but this requires all existing users to modify their workflow.

**Comment by AmrutaKawade** [comment]
I tried to retrieve commit message as mentioned here

https://stackoverflow.com/questions/63619329/github-action-get-commit-message

![image](https://user-images.githubusercontent.com/65217380/110434006-45110780-80d7-11eb-9c4e-1a758329e974.png)

![image](https://user-images.githubusercontent.com/65217380/110433844-07ac7a00-80d7-11eb-8ee4-b5e47da33d87.png)

But its not available

**Comment by AmrutaKawade** [comment]
I have released this fix and you can verify with v2 tag. but strange thing is Deployment Center UI seems to be changed.
![image](https://user-images.githubusercontent.com/65217380/110440498-bbfdce80-80de-11eb-87c2-9b9137ff3338.png)

**Comment by spellegrino021** [comment]
> I have released this fix and you can verify with v2 tag. but strange thing is Deployment Center UI seems to be changed.
> ![image](https://user-images.githubusercontent.com/65217380/110440498-bbfdce80-80de-11eb-87c2-9b9137ff3338.png)

Yes we recently changed the UI so if you are set up with Azure Pipelines you will see the classic Deployment Center.

**Comment by AmrutaKawade** [comment]
since this is released will close this issue
