### ISSUE TITLE
Deployment Failed with Error: Error: Resource "app-service-name" doesn't exist.

### ISSUE THREAD

**Issue by honey-ramgarhia** [Azure/webapps-deploy#112]
Hi, I am using this action to deploy my .NET 5 application on App Service. I have two jobs in my CD workflow. First is setup-infra which uses Terraform to create resources on Azure and second is build-and-deploy which deploys my code to the newly provisioned resource. But I'm getting **Deployment Failed with Error: Error: Resource "app-service-name" doesn't exist.** error. The AppService was created in the previous job and I checked on Azure portal it exists there as well so why does it throws this error?

Here are my build-and-deploy job's steps

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SERVICE_PRINCIPAL_CREDS }}

      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Dependencies
        run: dotnet restore
        
      - name: Test
        run: dotnet test --no-restore

      - name: Publish
        run: dotnet publish -c Release --no-restore -o '${{ env.AZURE_WEBAPP_PATH }}'

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: '${{ needs.setup-infra.outputs.app_service_name }}'
          package: '${{ env.AZURE_WEBAPP_PATH }}'
      
      - name: Azure Logout
        run: az logout`
`

**Comment by AmrutaKawade** [comment]
does this cred `SERVICE_PRINCIPAL_CREDS` have access to your app?

**Comment by honey-ramgarhia** [comment]
@AmrutaKawade Yes it does have access. It's a Service Principal object with Contributor role and access level at the Azure subscription.
I was actually able to deploy once using the pipeline by providing App Service name (in lowercase) statically. Something like this:

`app-name: 'my-app-service-name'`

 and I thought this could be the issue. My App Service name had some capital letters in it. Then I replaced the static name with the actual generated name but transforming it to lowercase but still it didn't worked.

Here is my TF file:

```
terraform {
  required_providers {
    random = {
      source = "hashicorp/random"
      version = "3.0.1"
    }
  }

  backend "azurerm" {
    resource_group_name = "resource_group_name"
    storage_account_name = "storage_account_name"
    container_name = "container_name"
    key = "terraform.tfstate"
    access_key = "access_key"
  }
}

provider "azurerm" {
    features {}
}

resource "azurerm_resource_group" "rg" {
    name = "DotnetCD-RG"
    location = "Central India"
}

resource "azurerm_app_service_plan" "asp" {
    name = "DotnetCD-ASP"
    location = azurerm_resource_group.rg.location
    resource_group_name = azurerm_resource_group.rg.name

    sku {
        tier = "Free"
        size = "F1"
    }
}

resource "azurerm_app_service" "as" {
    name                = "DotnetCD-AS"
    location            = azurerm_resource_group.rg.location
    resource_group_name = azurerm_resource_group.rg.name
    app_service_plan_id = azurerm_app_service_plan.asp.id

    site_config {
        dotnet_framework_version = "v5.0"
        use_32_bit_worker_process = true
    }
}
```

**Comment by AmrutaKawade** [comment]
Can you set `ACTIONS_STEP_DEBUG=true` in secrets and run pipeline and share debug logs? you can hide sensitive info from logs

**Comment by honey-ramgarhia** [comment]
Here is debug output

```
##[debug]Evaluating condition for step: 'Deploy'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Deploy
##[debug]Loading inputs
##[debug]Evaluating: needs.setup-infra.outputs.app_service_name
##[debug]Evaluating Index:
##[debug]..Evaluating Index:
##[debug]....Evaluating Index:
##[debug]......Evaluating needs:
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'setup-infra'
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'outputs'
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'app_service_name'
##[debug]=> '"dotnetcd-as"'
##[debug]Result: '"dotnetcd-as"'
##[debug]Evaluating: env.AZURE_WEBAPP_PATH
##[debug]Evaluating Index:
##[debug]..Evaluating env:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'AZURE_WEBAPP_PATH'
##[debug]=> './DotnetCD'
##[debug]Result: './DotnetCD'
##[debug]Loading env
Run azure/webapps-deploy@v2
  with:
    app-name: "dotnetcd-as"
    package: ./DotnetCD
    slot-name: production
  env:
    AZURE_WEBAPP_PATH: ./DotnetCD
    DOTNET_VERSION: 5.0.x
    ARM_CLIENT_ID: ***
    ARM_CLIENT_SECRET: ***
    ARM_SUBSCRIPTION_ID: ***
    ARM_TENANT_ID: ***
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
    DOTNET_ROOT: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet
##[debug]try-get AzureCLIAuthorizer
##[debug]"C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account show
##[debug]"C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" cloud show
##[debug]"C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account get-access-token
::add-mask::***
##[debug][GET] https://management.azure.com/subscriptions/***/resources?$filter=resourceType EQ 'Microsoft.Web%2FSites' AND name EQ '%22dotnetcd-as%22'&api-version=2016-07-01
Error: Deployment Failed with Error: Error: Resource "dotnetcd-as" doesn't exist.
##[debug]Deployment failed
##[debug]Node Action run completed with exit code 1
##[debug]AZURE_HTTP_USER_AGENT='GITHUBACTIONS_DeployWebAppToAzure_157f7bc885d97e85f5c3216e567c2c8d091702dbe8e0821f031b7fc0f97963d3'
##[debug]AZURE_HTTP_USER_AGENT=''
##[debug]Finishing: Deploy
```

Here is the screenshot for my App Service that got created.
![Screenshot 2021-02-26 162422](https://user-images.githubusercontent.com/25500071/109291633-34e36780-784f-11eb-989c-8eed47b561ed.png)

**Comment by honey-ramgarhia** [comment]
Ooh I see somehow "" are also attached to the App Service name.
