### ISSUE TITLE
Ability to swap slots?

### ISSUE THREAD

**Issue by larryclaman** [Azure/webapps-deploy#113]
Doesn't seem like it's possible with this action to use the best-practice deployment process of deploying an app to a staging slot, and then swapping with production to eliminate any downtime.  See https://docs.microsoft.com/en-us/azure/app-service/deploy-staging-slots

If this is possible, could you document?
If it's not currently possible, could you add it as a feature request?

**Comment by AmrutaKawade** [comment]
@larryclaman You can enable auto-swap for slots on portal and deploying to slot is supported in this action.

**Comment by larryclaman** [comment]
@AmrutaKawade Thanks, that does solve one use case, but not the broader feature of being able to use a GitHub action to swap slots. (as one can do with the Azure DevOps Task App Service Manage https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-app-service-manage?view=azure-devops)

Is the guidance to simply use the az cli for this?

**Comment by AmrutaKawade** [comment]
Yes. App Service Manage task capabilities are not available currently in this Task and az cli would be alternative.
@N-Usha can you check into this enhancement request?

**Comment by anrub** [comment]
Any updates on the ability to automate blue green deployments? really strange, that this is not a default use case for deployments.
