### ISSUE TITLE
Provide the commit message in the zip deploy API

### ISSUE THREAD

**Issue by nertim** [Azure/webapps-deploy#118]
The commit message exists in GITHUB_CONTEXT

Sample repo:
https://github.com/nertim/github-action-testapp-node

YML:
![image](https://user-images.githubusercontent.com/493476/112353025-8f25eb80-8c88-11eb-98e9-7e881e2b606b.png)

Commit message in output (line 231):
![image](https://user-images.githubusercontent.com/493476/112353105-a7960600-8c88-11eb-8526-2c6035b1ab3b.png)

**Comment by nertim** [comment]
@AmrutaKawade @JasonFreeberg @spellegrino021 FYI

**Comment by kaverma** [comment]
@Balaga-Gayatri is looking into this issue

**Comment by BALAGA-GAYATRI** [comment]
Hi @nertim released the changes with this feature.
