### ISSUE TITLE
Add log stream to deployment

### ISSUE THREAD

**Issue by dennisameling** [Azure/webapps-deploy#120]
Related to https://github.com/Azure/webapps-deploy/issues/119

Currently, when using this GitHub Action, no real-time deployment logs are shown, so it looks like the action is hanging. You won't see anything except for `Package deployment using ZIP Deploy initiated.` until the very end, where a link to the log files is shown:

![image](https://user-images.githubusercontent.com/17739158/113000986-a2e1be00-9170-11eb-9803-fce66f491b32.png)

When using [Azure's VS Code extension](https://docs.microsoft.com/nl-nl/azure/developer/javascript/tutorial/deploy-nodejs-azure-app-service-with-visual-studio-code?tabs=bash) to do a deployment, a real-time log stream is shown, so that you know exactly what the Azure service is currently doing. Could this please be added to this GH Action as well?

**Comment by kaverma** [comment]
HI @dennisamelin, can you please try enabling step debugging to get verbose logs - https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging

**Comment by dennisameling** [comment]
That works, but it'd be great to have this just for the `webapps-deploy` step. `ACTIONS_STEP_DEBUG` sets it for every step in the job, which is a bit overkill. I really like how the VS Code extension mentioned above is doing it currently, providing real-time updates on what's happening. Might be something to consider for the future? 😊
