### ISSUE TITLE
FAIL: run azure webapp deploy action using publish profile credentials

### ISSUE THREAD

**Issue by xcelsiorbosi** [Azure/webapps-deploy#124]
Hi Team, 
I came across a nasty bug that took me a few days to resolve. 

1) intially deploy on linux
2) wanted to try the webapp 'push' product so created a new web app and deployed win os
3) web app deployment failed non-stop, tried a million things and nothing worked
4) deleted webapp a few times and made a new one

5 -  (finally after 5 days)) reverted back to linux and used original  webapp name
6) success web app deployed. 

this leaves me to believe that  there is a config file attached to my git account and the webapp that is not available within my git repo that ties the webapp name to the 'Actions' deployment. 

Could I request a feature for automated environment migration (windows hosted from linux) as this bug had me doing tailspins with no real logs to diagnose.

**Comment by kaverma** [comment]
@BALAGA-GAYATRI , can you please look into this?
