### ISSUE TITLE
This action does not remove old files during upload!

### ISSUE THREAD

**Issue by reilem** [Azure/webapps-deploy#128]
I would expect that when you upload a "new" deployment, that all traces of previous deployments would be removed. However, I just tested this on our dev branch and I can with 100% certainty confirm that old files from old outdated deployments are STILL PRESENT.

I sincerely hope this is a bug and not intentional design, because keeping old files in an app service can lead to all sorts of nasty stuff:
- Storage consumption increase over time
- Attempting to run or compile old code can result in startup crash loop (this is what brought our dev servers down)
- Security leaks: if old keys/access codes are removed from repo they will still be there in the app service even after redeployment!!!

**Comment by BALAGA-GAYATRI** [comment]
@ehamai Can you have a look at this?

**Comment by reilem** [comment]
I eventually had to work around this problem by adding `WEBSITE_RUN_FROM_PACKAGE`=`1` in the configuration of my app service. Still not an ideal solution though.

**Comment by ArieJones** [comment]
Has there been any kind of update on this? It may be related to the current issue I am having with deployments... 

#138 

Not exactly wanting to napalm everything in the wwwroot directory without a clear understanding of ramifications. Like can I just nuke everything and then redeploy? Will that affect a redeploy?

**Comment by ArieJones** [comment]
So I have addressed my issue with deployments but can still see that these old files are hanging around.. .which is not good. If we were to wipe out the wwwroot folder items and then redeploy would that be sufficient to rectify things? I am unsure if there are any app service specific items that dwell within the folder that need to be hands off and unintentionally deleting them would cause an issue

**Comment by reilem** [comment]
You should be able to wipe them. Whenever I did there was no problem. I just got tired of having to do it manually, since there wasn't any clean way to automate it. So I just started using the WEBSITE_RUN_FROM_PACKAGE config.

**Comment by JasonFreeberg** [comment]
Hi @reilem, do you mind sharing the site name where you were having this issue? What OS and framework were you deploying (Flask, Express, .NET, Spring Boot)?

**Comment by reilem** [comment]
It is a Linux app service running a Node 12 LTS stack. The application is similar to express, an apollo-fastify graphql server.

**Comment by rabollin** [comment]
This has been fixed and not reproducible with latest bits.
