### ISSUE TITLE
Deploying to App Service Environment (ASE) runs forever

### ISSUE THREAD

**Issue by JasonFreeberg** [Azure/webapps-deploy#135]
Scenario: I am trying to deploy a container to an ILB App Service Environment. (ILB = Internal Load Balancer, so the application is not internet accessible). I am using a Service Principal to authenticate and deploy.
- Workflow file: https://github.com/JasonFreeberg/spring-petclinic/blob/master/.github/workflows/deploy-container.yml
- Live repro: https://github.com/JasonFreeberg/spring-petclinic/actions/runs/808931510

Problem: When deploying to the ASE, the webapps-deploy action runs indefinitely. The workflow file above deploys the same image to a multi-tenant Web App, and it takes only 20 seconds since it's only logging in and updating the LinuxFxVersion on the site. However, the job deploying to the ASE runs for up to 20 minutes (I cancelled it at that point)

Some thoughts: 
- What is the stopping case for the action? 
- Is it pinging the site after deploying, looking for a response? If so, with an ASE the action will never get a response. 
- Is there a timeout?

**Comment by jacobkring** [comment]
I believe I am also experiencing the same issue when trying to deploy to an app service environment. Is there any workaround or another way to deploy that someone can recommend?

**Comment by jacobkring** [comment]
Never mind! I read your post more thoroughly and used the example workflow file you shared as an example to deploy and update the version using the cli as well.

**Comment by BALAGA-GAYATRI** [comment]
@JasonFreeberg can you try adding a secret ACTIONS_STEP_DEBUG and set the value true and see if it helps debug the issue.

**Comment by BALAGA-GAYATRI** [comment]
@JasonFreeberg  Here are few insights

-  Stopping condition : within the action we don't have such stopping condition 

- but in the kudu utility functions from [pipelines-appservice-lib](https://github.com/microsoft/pipelines-appservice-lib) which we use for our action, we have [zipDeploy ](https://github.com/microsoft/pipelines-appservice-lib/blob/007a2087fe8bebfc96f98fcc2b4a907829083677/packages/appservice-rest/src/Kudu/azure-app-kudu-service.ts#L146) which polls the `response.header.location` if `response.statuscode==202
`
-  There is no timeout for this one as it polls indefinitely till you get either of these.
`result.status == KUDU_DEPLOYMENT_CONSTANTS.SUCCESS || result.status == KUDU_DEPLOYMENT_CONSTANTS.FAILED
`
- This kind of process doesn't exist for deploying images/containers so we don't face this issue there.

**Comment by haraldatbmw** [comment]
@BALAGA-GAYATRI You mentioned that zipDeploy is used. Is this deployment model compatible with an internal App Service Environment used for hosting the AppServices?

**Comment by mditz-intermediait** [comment]
Someone could resolve this issue?

**Comment by sgollapudi77** [comment]
`What is the stopping case for the action?
Is it pinging the site after deploying, looking for a response? If so, with an ASE the action will never get a response.
Is there a timeout?`
I think all these questions have been answered in the above comments. Please let us know if this issue is still happening by providing more details.

**Comment by sgollapudi77** [comment]
Closing this as all the questions were answered in the previous comments. Please feel free to re-open this issue if this problem persists.
