### ISSUE TITLE
Configure Debug Flag

### ISSUE THREAD

**Issue by jeancroy** [Azure/webapps-deploy#151]
So the Azure Deployment Center, configured with a Github Source seems to use this script running on Github action to build app before using zip deploy.

My issue is that asp.net application built this way seems to have the debug flag on.
As in `#if (Debug) .. #endif` preprocessor directive.  

It doesn't seem to be a slot setting, and it doesn't seem to be aware of web.config > system.web>compilation>debug

**Comment by BALAGA-GAYATRI** [comment]
@jeancroy can you try adding a secret **ACTIONS_STEP_DEBUG** and set the value **true** and see if it helps debug the issue.

**Comment by JasonFreeberg** [comment]
@jeancroy -- Is this the workflow file template that you're using? https://github.com/Azure/azure-functions-ux/blob/e926ad77fa8786c9d88c5ca8a575d427f9142e9b/server/src/workflows/2020-12-01/web-app-configs/aspnet-windows.config.yml

That's what we drop in users' repos when they set up GitHub Actions. I don't see the directive being set there. Is it enabled in your app config or something?

**Comment by fizgig** [comment]
I am having the same issue, it's pulling in my debug web.config instead of my release version.  Is there a fix for this?

**Comment by jeancroy** [comment]
1) Yes I had same file as [aspnet-windows.config.yml](https://github.com/Azure/azure-functions-ux/server/src/workflows/2020-12-01/web-app-configs/aspnet-windows.config.yml) except for placeholder like ~__sitename__`, they have been filled in.

2) I was able to fix my issue by adding 
   `/p:Configuration=Release`

At the end of
`run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\" `


3) This follow same logic as 
[dotnetcore-windows.config.yml](https://github.com/Azure/azure-functions-ux/server/src/workflows/2020-12-01/web-app-configs/dotnetcore-windows.config.yml)

Where release is forced using
`dotnet build --configuration Release`

4) Without forcing the flag the configuration comes from .csproj file.

But my csproj default to debug, this my dev env preference, not my deploy preference.

**Comment by shpraka** [comment]
Closing the issue, feel free to create new issue.
