### ISSUE TITLE
Introduce Projects from Azure Webapps deploy - github-actions

### ISSUE THREAD

**Issue by chaos-ui** [Azure/webapps-deploy#152]
https://docs.microsoft.com/en-us/azure/app-service/deploy-continuous-deployment?tabs=github#how-the-github-actions-build-provider-works

**Comment by BALAGA-GAYATRI** [comment]
@chaos-ui Can you explain the issue in detail?

**Comment by BALAGA-GAYATRI** [comment]
@chaos-ui If you are looking for documentation related to deployments using webapps-deploy action, you may refer [documentation](https://github.com/Azure/webapps-deploy#github-action-for-deploying-to-azure-web-app) here. It has sample workflows and guidelines.
