### ISSUE TITLE
Deploy to custom folder on Azure App Service

### ISSUE THREAD

**Issue by imuller** [Azure/webapps-deploy#154]
Hi!

How can i configure to deploy to a custom sub folder on Azure App Service? I tried different ways by setting it in the publish profile but it wont work. Always deploying to the wwwroot folder.

Thanks!

**Comment by imuller** [comment]
Any update on this? Currently pushing to the wwwroot folder also removes the other contents.

**Comment by imuller** [comment]
As a workaround i currently modified the deploy.cmd script located in C:\home\site\deployments\tools\deploy.cmd. Somewhere the DEPLOY_TARGET environment variable is set. You can overwrite it by setting it with a if condition by looking at the SCM_COMMIT_MESSAGE. Change the [REPOSITORY_NAME] with the name of your repository. It's not perfect but the script knows where to deploy.

`IF /I "%SCM_COMMIT_MESSAGE:[REPOSITORY_NAME]=%" neq "%SCM_COMMIT_MESSAGE%" (
  SET DEPLOYMENT_TARGET=%HOME%\site\wwwroot_new
)`

**Comment by BALAGA-GAYATRI** [comment]
Hi @imuller 

Please try with below mentioned steps.
1. Download your publish-profile and make below changes to it.
    

- Change Site Name from `your-site` to `your-site\folder\sub-folder`

- Change the Destination URL from `http://your-site.azurewebsites.net `to `http://your-site.azurewebsites.net/folder/sub-folder`

2. Go to the **azure portal -> your app  -> configuration->path mappings** and create a new entry there.

Virtual Path | Physical Path | Type
-- | -- | --
/folder/sub-folder | site\wwwroot\folder\sub-folder | Application

<br class="Apple-interchange-newline">

Hope it helps. Lets us know the results after trying these steps.

**Comment by rymdfarfar** [comment]
Any updates on this? @BALAGA-GAYATRI solution did not solve it for me.

**Comment by JasonFreeberg** [comment]
Looks like an opportunity for OneDeploy

**Comment by LycanII** [comment]
Hi All, 
I tried @BALAGA-GAYATRI solution it still deployed to the 'site\wwwroot' folder, any other solution I can try?

**Comment by alexpoontm** [comment]
> Hi All, I tried @BALAGA-GAYATRI solution it still deployed to the 'site\wwwroot' folder, any other solution I can try?

Hi, I got same issue about that. Have you find any workaround?

**Comment by bluefirepatrick** [comment]
bump.  I am trying to deploy a subdirectory of a git repo to an Azure App Service via actions.  ex: the repo has an /api and a /client directory and I just want to deploy /api as the root of the web service.  (I think this is the same issue as OP).  I believe that a .deploy file in the root will be ignored since I am using CI/CD.  Is there a setting in the yaml that can accomplish this?

**Comment by voltura** [comment]
Any updates?
I want to deploy webapp to wwwroot and web api to wwwroot\api 
Created virtual application path in azure.
Cannot get yml syntax to work in github actions web api still overwrites web app and puts web.config pointing to api in web root... I can however publish api and app via vs directly without using github actions and this works fine; web app in root and api in subfolder api

**Comment by voltura** [comment]
I solved it by modifying the environment variable **DEPLOYMENT_TARGET** before deploying. This variable is used by the deployment script _C:\home\site\deployments\tools\deploy.cmd_ (can be viewed in azure portal > web app > advanced tools > debug console). By modifying this variable before deployment from workflow the web app's files including web.config in wwwroot is not overwritten by the deployment of the API to wwwroot\api (the API path in my case, created virtual application path in azure).
<img width="1619" alt="work-around-modify-env-var" src="https://user-images.githubusercontent.com/2292809/170857540-9a33d5d2-7c38-4ce4-951e-17427645839b.png">

<img width="1041" alt="azure_path_mappings" src="https://user-images.githubusercontent.com/2292809/170857669-bcea29b8-465f-4129-818e-a21ae664e44f.png">

**Comment by girishpn** [comment]
Hi, 

I have tried by setting the target folder for deployment in deploy.cmd, but still going to wwwroot folder.
![image](https://user-images.githubusercontent.com/37323123/194283632-bae2f904-dde8-414d-8b53-015ac7788240.png)

**Comment by shpraka** [comment]
@imuller were you able to deploy to custom folder using DEPLOYMENT_TARGET environment variable?

**Comment by girishpn** [comment]
I am able to do it via ftp method in workflow. It works fine for me. Zip deploy method will wipe out existing folders in root directory

**Comment by shpraka** [comment]
@imuller checking again if it's still happening.

**Comment by shpraka** [comment]
I am closing the issue for now, feel free to re-open or create a new one if you run into an issue.

**Comment by John-Donalson** [comment]
so what is the fix, the deployment target?
