### ISSUE TITLE
Review branding of all App service actions on Marketplace

### ISSUE THREAD

**Issue by azooinmyluggage** [Azure/webapps-deploy#160]
For example 
![image](https://user-images.githubusercontent.com/6857119/120794129-71f97d00-c555-11eb-8bb5-918d470804b0.png)
and
![image](https://user-images.githubusercontent.com/6857119/120794164-80479900-c555-11eb-894c-f6ccaa0b8509.png)
and
![image](https://user-images.githubusercontent.com/6857119/120794216-8e95b500-c555-11eb-9fe0-cc25402bfacf.png)

**Comment by pulkitaggarwl** [comment]
@JasonFreeberg  can you please have a look at the branding and update / suggest as needed.

**Comment by JasonFreeberg** [comment]
@pulkitaggarwl , @N-Usha -- Should all actions be using the new Azure logo, or should each Action use its service logo (Web Apps uses web apps logo, Functions uses Functions logo, etc.)

**Comment by pulkitaggarwl** [comment]
@JasonFreeberg  
While publishing the action you need to choose from existing list of icons. I don't think today we would have all icons corresponding to each service.

**Comment by azooinmyluggage** [comment]
@saquibkhan to confirm this. 

> While publishing the action you need to choose from existing list of icons. I don't think today we would have all icons corresponding to each service.

**Comment by tulikac** [comment]
@btardif - can you please take a look at the branding? If we are going to use the Azure logo, it needs to be updated to the new one. Or we can use a separate logo based on each service.

**Comment by tulikac** [comment]
Had an internal discussion. We will do an overall branding review and closing this item.
