### ISSUE TITLE
Question: Is there a working example with docker-compose?

### ISSUE THREAD

**Issue by danielmoessner** [Azure/webapps-deploy#188]
I've got a django app with nginx.

I would like to auto-deploy it to an azure app service.

However I don't get docker-compose to work and auto deploy my code.

What do I need to change so that it works on azure?

At the moment my github actions look like this:
```

on:
  push:
    branches:
      - master
name: Linux_Container_Workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'checkout action'
      uses: actions/checkout@v2

    - name: 'login to azure'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 'create secrets.json for django'
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "secrets.json"
        json: ${{ secrets.DJANGO_SECRETS }}
        dir: 'tmp/'

#    - run: |
#        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/django-backend:${{ github.sha }}
#        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/django-backend:${{ github.sha }}

    - name: 'build docker app'
      run: docker-compose build


    - name: 'deploy to azure'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'my-app'
        publish-profile: ${{ secrets.PUBLISH_PROFILE_COMPOSE_APP }}
#        images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/django-backend:${{ github.sha }}'

```

**Comment by BALAGA-GAYATRI** [comment]
hey @danielmoessner ! You should pass [configuration-file](https://github.com/Azure/webapps-deploy/blob/45c59f7e52af49a907d6dc9cfef6fc715137838a/action.yml#L22) parameter in the input with the corresponding value as the compose file path. In that case you need not need to pass images field as input. You may refer this for a [sample workflow](https://github.com/BALAGA-GAYATRI/python_container_App/blob/main/.github/workflows/deploy.yml). Try this out and let us know if it’s  working.

**Comment by danielmoessner** [comment]
Thanks for your answer. I didn't understand that nginx was running already on those web services. Therefore, I tried to run it myself in docker-compose. I realized I didn't need to do that and went with a normal docker image. 
I will keep that sample workflow in mind. In case I need to deploy docker-compose at some point in the future.
Thanks.
