### ISSUE TITLE
Deployment failure marked as passed

### ISSUE THREAD

**Issue by thewilkybarkid** [Azure/webapps-deploy#189]
I've just had a run (https://github.com/PREreview/prereview/runs/3289511938) log:

```
Restarting app service: prereview-dev
Deployment passed
Restarted app service: prereview-dev
Successfully updated deployment History at ...
```

But it failed due to a misconfiguration, the deployment log containing:

```
INFO - Stopping site prereview-dev because it failed during startup.
```

Is it possible to check that the deployment has actually worked?

**Comment by BALAGA-GAYATRI** [comment]
hey @thewilkybarkid Can you add this secret in your repo `ACTIONS_STEP_DEBUG` and set its value to `true` to enable detailed debug logs and that might solve the issue. Also please share your workflow if the problem persists. Do let us know if it works.

**Comment by rahulaga-dev** [comment]
@thewilkybarkid : did you tried above suggestion and let us know if that helped ?

**Comment by rahulaga-msft** [comment]
@thewilkybarkid I am marking this issue closed for now. Please re-open if the above suggestion did not work out and share workflow.
