### ISSUE TITLE
Deployment does not work over Github Action

### ISSUE THREAD

**Issue by akbast** [Azure/webapps-deploy#191]
Hi,

I have an App-Service deployed on Azure in that I want to deploy with node application which is written in typescript. 

If I start the deployment via VS-Code Extension for Azure App Services, it works without a problem. I can see that my Service is deployed and it is usable.

If I try to deploy it from a Github Action, the deployment seems successful but the App-Service is not reachable anymore. I get Http-503 Error in the console. 

Followed tutorial here: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel

**Comment by BALAGA-GAYATRI** [comment]
hey @akbast Can you provide workflow and error logs here so that the issue can be found. Also please confirm if you are following the instructions provided in the [readme](https://github.com/Azure/webapps-deploy#create-azure-web-app-and-deploy-using-github-actions).

**Comment by akbast** [comment]
I could fix the problem with setting the WEBSITE_RUN_FROM_PACKAGE to true in my app service. The issue can be closed
