### ISSUE TITLE
Desktop

### ISSUE THREAD

**Issue by ladykraken** [Azure/webapps-deploy#195]
[LocalizedResourceName=(@%SystemRoot%\system32\shell32.dll,-21798)]
@mskraken
https://accounts.zoho.com/accounts/w/c/a?servicename=ZohoSupport&digest=AC-2YNXnN0N9crrKM9vdWJH6x9OB
b1-de3e9276-1910-42ea-b6cb-ecf06ad4ac33
[FunctionName("Counter")]
public static void Counter([EntityTrigger] IDurableEntityContext ctx)
{
    switch (ctx.OperationName.ToLowerInvariant())
    {
        case "add":
            ctx.SetState(ctx.GetState<int>() + ctx.GetInput<int>());
            break;
        case "reset":
            ctx.SetState(0);
            break;
        case "get":
            ctx.Return(ctx.GetState<int>());
            break;
    }
}

**Comment by kanika1894** [comment]
hey @ladykraken,

Can you please help us more in understanding your issue?

**Comment by BALAGA-GAYATRI** [comment]
@ladykraken this action repo issues page deals with only issues on webapps-deploy to azure using github workflows. Closing this as your issue seems to be not relevant for this repo.
