### ISSUE TITLE
Deployment failed when deploying to a Deployment Slot due to app name/slot name validation logic

### ISSUE THREAD

**Issue by j4fm** [Azure/webapps-deploy#197]
"Deployment Failed with Error: Error: Publish profile is invalid for app-name and slot-name provided. Provide correct publish profile credentials for app.

Looking at the validation logic, it splits the username by "__", but usernames configured by Azure App Service are of the format $appname(slotname), not $appname__slotname.

Therefore, it always fails to match and validate appname and slotname.

Note: This is via Azure Arc enabled App Service - this sets usernames in the format $appname(slotname) but the non-Azure Arc enabled App Service sets them in $appname__slotname.

Validations.ts

`let splitUsername: string[] = creds.username.startsWith("$") ? creds.username.toUpperCase().substring(1).split("__") : creds.username.toUpperCase().split("__");`

Workaround:

In the Workflow, set appname="appname(slotname)" and slotname="production".  This passes validation logic and also successfully deploys to the slot.

**Comment by BALAGA-GAYATRI** [comment]
Hi @j4fm Thank you for suggesting the workaround. This issue is being investigated and will let you know the solution.

**Comment by BALAGA-GAYATRI** [comment]
Hey @j4fm. We have the updated validation logic here in `LaylaLiu-gmail/webapps-deploy@v3` as a temporary fix. While we are working on more consistent solution, you can use the above if you don't want change your appname to "appname(slotname)".

**Comment by j4fm** [comment]
Thank you @BALAGA-GAYATRI, for the moment I have switched to testing out pure app service but will likely come back to azure arc app service, so this will be useful for then.

**Comment by kumaraksh1** [comment]
Closing the issue.

**Comment by technokarthyk** [comment]
facing the same issue again is there any way for permanent fix??? can anyone help on this??
