### ISSUE TITLE
Remove extra files on deploy

### ISSUE THREAD

**Issue by kodyang** [Azure/webapps-deploy#20]
I have noticed the deployment only creates new files and overwrites existing ones, but does not delete files not part of the deployment. This is causing our workspace to be cluttered and may lead to harder to pinpoint issues in the future.

Is there the option to delete the old files as new ones are deployed?

This is a feature available through other [existing deployment options](https://stackoverflow.com/questions/32079606/how-can-i-delete-existing-files-when-deploying-an-asp-net-5-web-app-to-azure)

**Comment by eaarora-ms** [comment]
@kodyang The existing deployment options that you have mentioned is msdeploy, however, we have started using zipdeploy in actions as well as in our newer tasks. 
According to the documentation here: https://docs.microsoft.com/en-us/azure/app-service/deploy-zipdeploy Deletes the files left over from a previous deployment. However the zip deploy will only delete files that were part of a previous deployment and are not in the deployment artifact.

**Comment by compulim** [comment]
@eaarora-ms your link is 404.

![image](https://user-images.githubusercontent.com/1622400/82750350-6f6e2000-9d64-11ea-979d-b78373a34748.png)

Agree with @kodyang, using `azure/webapps-deploy` to deploy, it don't remove existing files, making the web app very difficult to debug because of extraneous files (development environment != production web app).

You can repro by deploying a normal Node.js web app, then rename `index.js` to `something-else.js` and deploy again. On Kudo/SCM, you will see the `index.js` still exists on the disk.

**Comment by ThomasShaped** [comment]
I believe the correct link is https://docs.microsoft.com/en-us/azure/app-service/deploy-zip

> However the zip deploy will only delete files that were part of a previous deployment and are not in the deployment artifact.

@eaarora-ms This hasn't been my experience. My application has always been deployed via GitHub Actions but old project files still existed inside the webapp after they were deleted from my GitHub repo.

**Comment by asilverstein** [comment]
What is the status of this issue? It's very important to start each deployment with a clean (empty) target directory. Currently this is a blocking issue for using webapps-deploy.

**Comment by AmrutaKawade** [comment]
We use Kudu REST API for deployment. there is already [bug](https://github.com/projectkudu/kudu/issues/2822) on kudu team for this

**Comment by asilverstein** [comment]
Amruta, that bug was last responded to by the team in 2018.

**Comment by AmrutaKawade** [comment]
> @eaarora-ms your link is 404.
> 
> ![image](https://user-images.githubusercontent.com/1622400/82750350-6f6e2000-9d64-11ea-979d-b78373a34748.png)
> 
> Agree with @kodyang, using `azure/webapps-deploy` to deploy, it don't remove existing files, making the web app very difficult to debug because of extraneous files (development environment != production web app).

for different enviornments you can use slots https://docs.microsoft.com/en-us/azure/app-service/deploy-staging-slots

**Comment by AmrutaKawade** [comment]
> Amruta, that bug was last responded to by the team in 2018.

We are following up with Kudu team for this issue. But currently we are unable to repro this. Can you share repro steps?

**Comment by asilverstein** [comment]
The repro was stated by @kodyang at the top of this issue, and has not changed: "The deployment only creates new files and overwrites existing ones, but does not delete files not part of the deployment"

**Comment by aksm-ms** [comment]
Since this issue is on Kudu API which action uses please raise issue under [https://github.com/projectkudu/kudu/issues/](https://github.com/projectkudu/kudu/issues/ ). Closing the issue.

**Comment by PetrKaterinak** [comment]
Over six years old issue and still not solved? That is terrible, especially if I'm reading php class files in specific folders and performing actions on them using Reflection. Old files, which are no longer in git causing errors because of their different structure.

**Comment by vitoras** [comment]
It's astonishingly amateurish that this is still an issue to this day.

**Comment by boomlinde** [comment]
@aksm-ms Kudu doesn't accept new issues because it's no longer maintained and has been archived. The problem is then on your end: you're relying on unmaintained software that causes bugs downstream, and you should not. Please reopen the issue.

**Comment by kumaraksh1** [comment]
This issue is quite old and there was no active conversation so we could not look into the bug.
Let's start the investigation now and we will come back on it.

**Comment by kumaraksh1** [comment]
Kudu repo is archiveed so i reopened this issue :)

**Comment by prathambande** [comment]
Hello
You can use the `clean` parameter to delete existing files before deploying:
```
- uses: azure/webapps-deploy@v3
  with:
    app-name: your-app-name
    package: ./your-package
    clean: true
```
**Note: This is available in v3 only.** 
Please do message here if you face any issues!

**Comment by prathambande** [comment]
Closing this issue as the solution was provided about a month ago and there have been no follow-up. 
If anyone still faces issues, feel free to reopen this issue or create a new one and we'll be happy to help.
