### ISSUE TITLE
GitHub actions pipeline fails, but deployment is successful.

### ISSUE THREAD

**Issue by AustinWise** [Azure/webapps-deploy#200]
I have [an application](https://github.com/AustinWise/DinnerKillPoints) that I updated to .NET 6 RC2. I'm using the early access support in Azure App Services for .NET 6.

See [this pipeline run](https://github.com/AustinWise/DinnerKillPoints/runs/3916854153?check_suite_focus=true). The pipeline is marked as failed. It has these error messages:

```
Failed exitCode=1, command="kudusync" -v 50  -f "D:\local\Temp\zipdeploy\extracted" -t "D:\home\site\wwwroot" -n "D:\home\site\deployments\eb83bb8a398d41519ffcc04f3e439eb9\manifest" -p "D:\home\site\deployments\3256fa236268404b9d4ca54fd9658548\manifest" -i ".git;.hg;.deployment;deploy.cmd"
An error has occurred during web site deployment.
Error: The target file "D:\home\site\wwwroot\wwwroot\Identity\lib\bootstrap\LICENSE" is a directory, not a file.\r\nD:\Program Files (x86)\SiteExtensions\Kudu\94.30524.5227\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"
Error: Failed to deploy web package to App Service.
Error: Deployment Failed with Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
```

Despite the pipeline for deploy being marked as failed, the changes from [that commit](https://github.com/AustinWise/DinnerKillPoints/commit/df3f07418091107c4b35a8082beadfeea314cfb0) are [live on my website](https://dinnerkillpoints.azurewebsites.net/Home/About).

# What I expected to happen

I would expect on or the other of these to happen:

* the pipeline fails and the website is *NOT* updated
* the pipeline succeeds and the website is updated

Having the pipeline fail and the website updated is most unexpected

**Comment by AustinWise** [comment]
I took a look at the file `D:\home\site\deployments\3256fa236268404b9d4ca54fd9658548\manifest` and see these lines:

```
wwwroot\Identity\lib\bootstrap\LICENSE
wwwroot\Identity\lib\bootstrap\LICENSE\LICENSE
```

However when I do a `dotnet publish` locally, I only see the file `wwwroot\Identity\lib\bootstrap\LICENSE`.

This file is being feed into an invocation of `kudusync`:

```
kudusync -v 50  -f "D:\local\Temp\zipdeploy\extracted" -t "D:\home\site\wwwroot" -n "D:\home\site\deployments\5cf69452c7844fc789d38983aa41b625\manifest" -p "D:\home\site\deployments\3256fa236268404b9d4ca54fd9658548\manifest" -i ".git;.hg;.deployment;deploy.cmd"
```

I have not yet found out what is generating this erroneous input for `kudusync`.

**Comment by AustinWise** [comment]
Looking at the existing site directory, there is indeed the `wwwroot\Identity\lib\bootstrap\LICENSE\LICENSE` file.

```
Directory of D:\home\site\wwwroot\wwwroot\Identity\lib\bootstrap\LICENSE

10/18/2020  08:24 PM    <DIR>          .
10/18/2020  08:24 PM    <DIR>          ..
05/13/2021  08:52 PM             1,153 LICENSE
```

So it seems the `kudusync.net` program can't handle directories turning into files between deploys.

One option might be to fix `kudusync.net`.

**Comment by AustinWise** [comment]
I have a PR to KuduSync.NET that may address the problem: https://github.com/projectkudu/KuduSync.NET/pull/30

**Comment by RichMercer** [comment]
I wonder if this isn't a Kudu issue at all because I see pretty much the same thing when running `dotnet build` on my newly upgraded .NET 6.0 solution on a Mac. Seems a but of a coincidence.

/usr/local/share/dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk.Razor/targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(616,5): error MSB3024: Could not copy the file "/Users/rich/.nuget/packages/microsoft.aspnetcore.identity.ui/6.0.0/staticwebassets/V5/lib/bootstrap/LICENSE" to the destination file "/Users/rich/GitHub/***/src/website/wwwroot/Identity/lib/bootstrap/LICENSE", because the destination is a folder instead of a file. To copy the source file into a folder, consider using the DestinationFolder parameter instead of DestinationFiles. [/Users/rich/GitHub/***/src/***.Web/***.Web.csproj]

**Comment by AustinWise** [comment]
@BALAGA-GAYATRI I'm going to close this and replace with #201, which explains the problem more crisply.

@RichMercer I think the file moving inside the `Microsoft.AspNetCore.Identity.UI` package when upgrading to v6.0.0 is the common element between your problem and my problem. For your bug, perhaps there is a bug in the `Microsoft.NET.Sdk.Razor.StaticWebAssets.targets` file or the `Copy` MSBuild task it uses.
