### ISSUE TITLE
Deployment fails when directory is replaced with a file of the same name

### ISSUE THREAD

**Issue by AustinWise** [Azure/webapps-deploy#201]
I'm using .NET 6 on Windows on Azure App Services. The steps to reproduce in `cmd.exe` are roughly:

1. `git init`
1. `dotnet new web`
2. `md wwwroot`
3. `md wwwroot\test.txt`
4. `echo test > wwwroot\test.txt\test.txt`
5. `git add .`
6. `git commit -m inital`
7. Push to GitHub
8. Using ClickOps&#8482; in the Azure Portal, create a new App Service with the following properties
    1. Windows Host
    2. .NET 6
    3. Continuous deployment from your GitHub repo
9. Wait for the GitHub action to complete successfully
10. `rd /s /q wwwroot\test.txt`
11. `echo test > wwwroot\test.txt`
12. `git add .`
13. `git commit -m move`

Expected result: GitHub action completes successfully
Actual result: GitHub action fails

You can these steps being followed in this GitHub Repo: https://github.com/AustinWise/WebAppsDeployRepro/commits/master

I believe the root cause is the KuduSync.NET program that this GitHub action uses does not handle directories being replaced with files. I have a fix at projectkudu/KuduSync.NET#30 . I have not tried reproducing this on a Linux host, but for what it's worth the node.js version of KuduSync has the same problem when run on Windows (see projectkudu/KuduSync#40 ).

If you are curious how you might encounter this in the wild, I found this when upgrading from .NET 5 to 6. Specifically the ` Microsoft.AspNetCore.Identity.UI` package version 5.0.7 places a file at `wwwroot\Identity\lib\bootstrap\LICENSE\LICENSE`. In the 6.0.0 version of the package the file is moved up to `wwwroot\Identity\lib\bootstrap\LICENSE`.

**Comment by shpraka** [comment]
@AustinWise is it still happening?

**Comment by shpraka** [comment]
@AustinWise could you please update the scenarios tested on [this PR](https://github.com/projectkudu/KuduSync.NET/pull/30) so that we can go ahead with the PR?

**Comment by sgollapudi77** [comment]
This issue is fixed with the [PR.](https://github.com/projectkudu/KuduSync.NET/pull/30) And the changes are released with this [PR.](https://github.com/projectkudu/kudu/pull/3441)
