### ISSUE TITLE
Virtual Application Support

### ISSUE THREAD

**Issue by VILLAN3LL3** [Azure/webapps-deploy#202]
The issue #33 is marked as stale.
That's why I opened a new issue:
Are there any news regarding the virtual application support for azure web apps?
If not: Is there a workaround I can use to deploy a web app to a virtual application folder of an azure web app?
Thanks!

**Comment by shpraka** [comment]
@VILLAN3LL3 is this targeted for app service on Windows or Linux?

**Comment by VILLAN3LL3** [comment]
@shpraka The app service runs on Windows

**Comment by shpraka** [comment]
@VILLAN3LL3 See if this helps: https://learn.microsoft.com/en-us/azure/app-service/configure-common?tabs=portal#map-a-url-path-to-a-directory.

**Comment by shpraka** [comment]
@VILLAN3LL3 checking again if the above documentation was able to help you.

**Comment by VILLAN3LL3** [comment]
@shpraka Sorry for the late reply. I had solved the challenge differently at that time by deploying the frontend in the wwwroot directory of the backend. But the documentation sounds like it could be helpful. Thanks!

**Comment by shpraka** [comment]
@VILLAN3LL3 Sounds good. I am closing this issue. Feel free to create new issue if you ran into any issues.
