### ISSUE TITLE
https://docs.microsoft.com/azure/virtual-machines/managed-disks-overview

### ISSUE THREAD

**Issue by ladykraken** [Azure/webapps-deploy#207]
Fixed Typo  
 ​    Azure Unmanaged Data Disks have a maximum size of 4095 GB. To use **disks** larger than 4095 GB use [Azure Managed Disks](https://docs.microsoft.com/azure/virtual-machines/managed-disks-overview)

**Comment by rahulaga-dev** [comment]
@ladykraken : this repos issues deal with webapps-deploy GitHub Actions, closing this for now. Feel free to open if you see any issue with this action (please provide more contextual information)

**Comment by ladykraken** [comment]
@rahulaga-msft
Thank you for the tip!
