### ISSUE TITLE
I am sharing 'theladykproject.wordpress.2021-12-16.000.xml' with you from WPS Office

### ISSUE THREAD

**Issue by ladykraken** [Azure/webapps-deploy#208]
WPS Office: Complete office suite with PDF editor

Here's the link to the file:
https://us.docworkspace.com/d/sICStu5CTAZinzo4G

Shared from WPS Office:
https://kso.page.link/wps

**Comment by rahulaga-dev** [comment]
@ladykraken : this repos issues deal with webapps-deploy GitHub Actions, closing this for now. Feel free to open if you see any issue with this action (please provide more contextual information)
