### ISSUE TITLE
Not enough space on Disk, Failing to Deploy to  Azure app Service

### ISSUE THREAD

**Issue by nyongonyirenda** [Azure/webapps-deploy#210]
Hi my react app is very small, i am trying to deploy it to azure app service but i am getting an error on deployment. 

Cleaning up temp folders from previous zip deployments and extracting pushed zip file C:\local\Temp\zipdeploy\nbtme5br.zip (111.13 MB) to C:\local\Temp\zipdeploy\extracted
There is not enough space on the disk.\r\n
Error: Failed to deploy web package to App Service.
Error: Deployment Failed with Error: Package deployment using ZIP Deploy failed. Refer logs for more details.

**Comment by rahulaga-dev** [comment]
@nyongonyirenda its targeted for Linux or windows app service ?

**Comment by nyongonyirenda** [comment]
> @nyongonyirenda its targeted for Linux or windows app service ? Also do you more logs to help understanding issue "_**Refer logs for more details..**_"

Hi I thought I had replied, its windows app service. Is the space error coming from on windows or github?

**Comment by rahulaga-msft** [comment]
@nyongonyirenda we will look into it. Meanwhile, under which app service plan your app is deployed?

**Comment by nyongonyirenda** [comment]
> @nyongonyirenda we will look into it. Meanwhile, under which app service plan your app is deployed?

Hi, currently it's in the free plan, which has a shared 1GB space which is mostly free? Could this be the reason?

**Comment by shpraka** [comment]
@nyongonyirenda it could be one reason. You could think of changing plan to use more resources appropriately. Please find more details for plans here: https://azure.microsoft.com/en-in/pricing/details/app-service/linux/

**Comment by kumaraksh1** [comment]
Hi @nyongonyirenda,
I am closing this issue for now. 
Kindly let us know after changing the plan if issue still exists.

You can always re-open/re-create the same issue.
