### ISSUE TITLE
If symlinks are removed after their target file during a deploy, the deploy fails

### ISSUE THREAD

**Issue by mcdurdin** [Azure/webapps-deploy#211]
For example, I had removed the npm package acorn from a website and attempted to deploy.

The node_modules/acorn/ folder was removed successfully, but the node_module/.bin/acorn symlink, which points to ../acorn/bin/acorn (i.e. node_modules/acorn/bin/acorn) cannot be removed, with the error: `Error: ENOENT: no such file or directory, stat '/home/site/wwwroot/stripe-node/node_modules/.bin/acorn'` (presumably because the deploy script attempts to follow the symlink rather than checking the link itself).

Workaround was to manually remove the symlink.

**Comment by rahulaga-msft** [comment]
@mcdurdin is this targeted for app service on Windows or Linux?

**Comment by mcdurdin** [comment]
> @mcdurdin is this targeted for app service on Windows or Linux?

Linux

**Comment by joshmedeski** [comment]
According to https://github.com/Azure-App-Service/KuduLite/blob/dev/Kudu.Services/Deployment/PushDeploymentController.cs#L903 there is a `WEBSITE_ZIP_PRESERVE_SYMLINKS` environmental variable that can be set to properly preserve symlinks in the zipped package. My team is trying this we will report back if/how we got it working.

**Comment by shpraka** [comment]
> I've not seen it happening recently but I don't think I have removed any node modules from any websites recently, so that's probably not surprising.

@mcdurdin I will close it then. Feel free to re-open it if you come across the issue again.
