### ISSUE TITLE
WebJob deployment fails with CODE:414

### ISSUE THREAD

**Issue by venkatadorisala** [Azure/webapps-deploy#214]
I'm using `webapps-deploy@v2` action to deploy .net core web job build artifact into Azure app service.  But it's giving below error everytime.

```
Run azure/webapps-deploy@v2
  with:
    app-name: web-app-test-eu-xxxxxxxxxxxxx-001
    package: .
    publish-profile: ***
    slot-name: production
  env:
    AZURE_WEBAPP_NAME: web-app-test-eu-levomethanol-001
    AZURE_WEBAPP_PACKAGE_PATH: .
    DOTNET_VERSION: 3.1.100
    BUILD_CONFIGURATION: Release
    BINARIES: ./app_data/jobs/continuous/XX.Integration.xxxxxxxx.WebJobs
    JAVA_HOME_11.0.14_x64: C:\hostedtoolcache\windows\jdk\11.0.14\x64
    JAVA_HOME: C:\hostedtoolcache\windows\jdk\11.0.14\x64
    JAVA_HOME_11_0_14_X64: C:\hostedtoolcache\windows\jdk\11.0.14\x64
    DOTNET_ROOT: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet

Package deployment using ZIP Deploy initiated.
Error: Failed to deploy web package to App Service.
Error: Deployment Failed with Error: Error: Failed to deploy web package to App Service.
Request-URI Too Long (CODE: 414)
App Service Application URL: http://web-app-test-eu-xxxxxxxxxxxxx-001.azurewebsites.net


```
I guess that it's due to the length of the app service name. Since the same workflow works well with other app services which have 1 character less in the name  For e.g below app services gets deployed successfully with same workflow.

```
http://web-app-dev-eu-xxxxxxxxxxxxx-001.azurewebsites.net
http://web-app-uat-eu-xxxxxxxxxxxxx-001.azurewebsites.net
http://web-app-prd-eu-xxxxxxxxxxxxx-001.azurewebsites.net
```

The error doesn't point the exact root cause so it's kind of very generic. Any pointer to fix ?

**Comment by carlos8k** [comment]
@venkatadorisala did you find a solution for this issue? I'm facing the same problem.

**Comment by rabollin** [comment]
@JasonFreeberg - Please check this issue out, it is with Java on Windows.

**Comment by JasonFreeberg** [comment]
@rabollin It doesn't seem like this is at all specific to Java. Their logs say that the request failed with `Request-URI Too Long (CODE: 414)`. Looks like our frontends are rejecting the deployment request because the URL is too long?

**Comment by JasonFreeberg** [comment]
Possibly related to #192 -- the action is sending the commit message in the deployment request. If the commit message is too long, then the deployment request fails. 

PR from community: https://github.com/Azure/webapps-deploy/pull/226

**Comment by kumaraksh1** [comment]
Closing this issue, we have merged the fix of this issue and it will be released by 1st week of december.
