### ISSUE TITLE
Container Deploy very slow using NodeJs

### ISSUE THREAD

**Issue by gabrielknot** [Azure/webapps-deploy#216]
I'am developing an pipeline to deploy several applications on azure Webapps/Functions. But using azure/webapps-deploy@v2 with container application we get an particular problem, the deploy was executed as expected, and the function was up and running with the app. But the action get into a loop trying to redeploy the aplication several times and stuck on Github Actions until fail by timeout.

Can you help us?

**Comment by alfjjacob** [comment]
Facing the same issue. Deploying a ReactJS app via container registry is stuck after 'Restarted app service' message. In my case, it does NOT seem be getting into the re-deployment loop though. The App seems to be running as well

![image](https://user-images.githubusercontent.com/856877/153293245-4d839eb8-a09e-45fb-b7df-3f13212de017.png)

**Comment by rahulaga-msft** [comment]
@alfjjacob : we are looking into this performance issue, between can you please provide time taken for specific steps in azure/webapps-deploy@v2 ? also the time it took in the build phase.

**Comment by alfjjacob** [comment]
@rahulaga-msft - Build is taking ~5secs but the deploy is stuck for several minutes 
![image](https://user-images.githubusercontent.com/856877/153434368-515e0839-3eee-4322-ae4a-2cb0bf7b8a6b.png)

**Comment by gabrielknot** [comment]
UPDATE: Having this same issue with any container deploy to WebApp, when the deploy hapens with Azure Functions the action works as expected.

PS: I made a mistake when I said this issue causes a loop, the deploy just stuck after conclusion and the log "Deployment passed!" without make any loop. The pipeline just stuck on this step, but the application update reflects on Azure Webapp.

**Comment by gabrielknot** [comment]
UPDATE: I tried to resolve this issue to open a PR on this repository, and I've found the function where the problem happens, but I cant resolve this without broken another feature on this action.
To resolve this issue, I just remove the if statement which calls the addAnnotation method (from 'azure-actions-appservice-rest/Utilities/AnnotationUtility')  on method    UpdateDeploymentStatus and the action works deploying containers in functions and webapp's. 

The method can be found at /src/DeploymentProvider/Providers/WebAppDeploymentProvider.ts

**Comment by rabollin** [comment]
Reviewing the deployment step to determine why it is taking longer

**Comment by shpraka** [comment]
We are tracking this issue as https://github.com/Azure/webapps-deploy/issues/229.
