### ISSUE TITLE
Is this also suitable for use in azure function deployments for containers?

### ISSUE THREAD

**Issue by boris-tarasov-maersk** [Azure/webapps-deploy#223]
While trying to follow Azure Function app deployment configuration UI in Azure portal I am getting following example of yaml pipeline generated:

![image](https://user-images.githubusercontent.com/75432520/159659567-8f55d07e-77ca-4bc4-ae85-1477f2b341ab.png)

**Comment by JasonFreeberg** [comment]
@boris-tarasov-maersk Yes it should work the same, but thanks for the feedback. I filed a WI on our backlog to clear up the confusion.
