### ISSUE TITLE
Error on deploying artifact to azure app service

### ISSUE THREAD

**Issue by boat-priyanka-agrawal** [Azure/webapps-deploy#225]
Hi,
I am using the webapps-deploy v2 github action to deploy artifact to azure app service, and getting the following error -

**Step Details –**
Run azure/webapps-deploy@v2
  with:
    app-name: test
    publish-profile: ***
    package: ./pl/public
    slot-name: production

**Error Message -** 
Package deployment using ZIP Deploy initiated.
Fetching changes.
Cleaning up temp folders from previous zip deployments and extracting pushed zip file D:\local\Temp\zipdeploy\yd3yr1ey.zip (47.91 MB) to D:\local\Temp\zipdeploy\extracted
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
Error: Failed to deploy web package to App Service.
Error: Deployment Failed with Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
App Service Application URL: http://test.azurewebsites.net/

**Comment by JasonFreeberg** [comment]
Assigned to me, need to create WI for Windows

**Comment by kumaraksh1** [comment]
Hey @boat-priyanka-agrawal,
Could you follow the given issue which has some workaround for your issue? 
https://github.com/microsoft/dotnet/issues/234

And let us know, if it resolves your issue or not.

**Comment by kumaraksh1** [comment]
@boat-priyanka-agrawal Please let me know if suggested workaround works for you. 
We will be closing this issue on 25th November 2022.
You can always re-open/create the issue again.
