### ISSUE TITLE
Use the new `/api/publish/` API for deployment

### ISSUE THREAD

**Issue by JasonFreeberg** [Azure/webapps-deploy#238]
There is a new deployment API, `/api/publish/` which has many more features over the `/zipdeploy/` API. It's currently used in the Azure CLI, plugins for Maven and Gradle, and it would be great to see it used here as well.

**Comment by surenderssm** [comment]
As discussed with @tulikac , @sgollapudi77 let's scope this in. This will help us in maintaining the consistency across the clients.

**Comment by sgollapudi77** [comment]
This feature is implemented in the PR: #360. With the new release of web-apps-deploy@v3, you will be deploying using Publish api instead of Zipdeploy.
https://learn.microsoft.com/en-us/azure/app-service/deploy-zip?tabs=cli#kudu-publish-api-reference
