### ISSUE TITLE
App Service Cannot Deploy Via GitHub Actions on B1 Plan

### ISSUE THREAD

**Issue by ThePieMonster** [Azure/webapps-deploy#242]
I am using the Azure App Web Service B1 plan that has only 1 slot. I am trying to use GitHub Actions web-deploy to deploy the Node.js application. 

I have code snippets of the issue on StackOverflow below, but it seems I am unable to deploy using this app plan. 

https://stackoverflow.com/questions/73145205/azure-app-service-publish-profile-is-invalid

**Comment by shpraka** [comment]
@ThePieMonster Can you please share some more details here? The link mentioned in the above comment is broken.

**Comment by ThePieMonster** [comment]
You can remove this inquiry.

**Comment by DigitalMystery** [comment]
@ThePieMonster @shpraka  I know this was a while ago, but what was needed for this?  I am actually running into the same issue when trying to deploy to B1.  I removed the slot-name from the .yml file already, but it still seems to want to deploy there and just hangs.
