### ISSUE TITLE
app-name setting incorrect when creating GH action from portal

### ISSUE THREAD

**Issue by dwhieb** [Azure/webapps-deploy#25]
Apologies if this isn't the correct place to report this issue - feel free to direct me elsewhere!

When I set up deployment using GitHub Actions from the Azure Portal, Azure automatically creates a workflow using the webapps-deploy action in my repository, with the following setting:

```yml
with:
  app-name: 'my-app(slotname)'
  slot-name: 'slotname'
```

However, this format for the `app-name` property fails validation when the webapps-deploy action runs, on these lines:

https://github.com/Azure/webapps-deploy/blob/8d236f5bdbe1cbc38ab6ea06baae520deaefd0cb/src/ActionInputValidator/Validations.ts#L29-L43

The field needs to be formatted this way in order to pass validation:

```yml
with:
  app-name: 'my-app'
  slot-name: 'slotname'
```

Once I changed this setting in my workflow config file, deployment worked fine.

This issue is to request two changes:
- fix the workflow file generated by the Azure Portal so that it follows the correct format for the `app-name` property (possibly not the right place to request this - sorry about that)
- update the documentation in this repo to include information about the format of the `app-name` and `slot-name` fields (the `slot-name` field doesn't currently appear in any of the documentation for this repo)

**Comment by eaarora-ms** [comment]
@dwhieb Thanks for pointing this out. Adding this to our list of future enhancements.
