### ISSUE TITLE
Is there anything to move files/folders from azure blobstorage after the out-of-the-box deployment is done?

### ISSUE THREAD

**Issue by ashishgururani1** [Azure/webapps-deploy#252]
web-app1 is deployed using the standard github connection and the default generated yml; and that is working as expected. Now, github source does not have some files like licenses.txt that is needed for the application to run (and we can't keep those files in github source control). Is there a way to add a deployment step to copy files from azure blob storage to the web app folder?

This is a .NET based app running on windows. 

For example, if the web app already has this folder structure 
C:\home\site\wwwroot\Folder1
C:\home\\site\wwwroot\\File1.text

And the blob storage has this folder structure 
myazureblobstorage\containers\web-app1\license.txt
myazureblobstorage\containers\web-app1\Folder3\file2.txt

Is there something that can be run as part of the deployment that will move the blob storage files to the web app? In this example the web app will become - 

C:\home\site\wwwroot\Folder1
C:\home\site\wwwroot\File1.txt
C:\home\site\wwwroot\license.txt
C:\home\site\wwwroot\Folder3\file2.txt

**Comment by shpraka** [comment]
@ashishgururani1 You can scm site to upload the file you want to site folder. 

If you are using Linux App service use <scm-url>/newui/fileManager. 

And if you are using Windows App Service, you can go to debug console and upload the file to site folder.

**Comment by ashishgururani1** [comment]
Hello - Thank you so much for your response. It's a windows based app service. I was thinking of more of a automated solution since the automated deployments happen often that will run after the stock deployment. So, there is no yaml commands that can be added to do copy some files as the last step?

> @ashishgururani1 You can scm site to upload the file you want to site folder.
> 
> If you are using Linux App service use /newui/fileManager.
> 
> And if you are using Windows App Service, you can go to debug console and upload the file to site folder.

**Comment by shpraka** [comment]
@ashishgururani1 is you ask something similar to this issue #161?

**Comment by shpraka** [comment]
Closing this as it looks similar to #161. We should try to cover this use case when we support post deployment execution.
