### ISSUE TITLE
Upgrade webapps-deploy to Node 16

### ISSUE THREAD

**Issue by LennartMart** [Azure/webapps-deploy#253]
See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by shpraka** [comment]
@LennartMart Thanks for the proposal. This is in our backlog, will keep you posted. 

Let me know if you're interested in taking it forward.

**Comment by shpraka** [comment]
We have updated the version in our latest release. Feel free to create a new issue in case of any issues. Closing this issue.
