### ISSUE TITLE
Preserve target folder content

### ISSUE THREAD

**Issue by zeniale** [Azure/webapps-deploy#254]
In my case I have an AppService on Azure where I have a root folder, where I publish the frontend, and an API folder where I publish the WebApi. The publication of these folders is done by two Actions of two different repositories. The problem is that publishing cleans the destination folder, so publishing one part of my project deletes the other. Is there an option to allow the TargetFolder to be left intact?

**Comment by John-Donalson** [comment]
this is completed but is there a solutions to this

**Comment by shpraka** [comment]
@John-Donalson This is not supported yet. Re-opening it to keep track, we are adding this in our backlog.

**Comment by John-Donalson** [comment]
i feel like i have something close with setting the target destination prior to deployment, setting zip deploy destination url in publish profile as well as app url, and restarting the app after deployment; but SCM do not delete also has to be set and so far only working with msbuild.exe for .net and npm+vue; msbuild official action will wipe… too many steps though

**Comment by sgollapudi77** [comment]
Related to #209 . Closing this as duplicate.
