### ISSUE TITLE
Corrupt zip file when deploying?

### ISSUE THREAD

**Issue by olaj** [Azure/webapps-deploy#26]
I'm not sure this is an issue with this action or something on Azure but i try here first.

My deployments has worked fine for a while but when i tried to deploy today i started to get these errors in the eventlog on Azure.

`ZIP_SUPPORT::OpenZipFile(861): Failed to read central end of central directory record due to signature mismatch. (Path:"\\?\d:\local\SitePackages\812114890.zip" Err:0x8007026a)`

`Failed to open zip file \\?\d:\local\SitePackages\812114890.zip. Error: 0x8007026a`

What i've tried.

- Different deployment slots.
- Tried the v2 version of the webapps-deploy
- Tried to update the publish-profile secret.
- Downloaded the zip file and extracted it without issues.
- Tried to make it a bit smaller by deleting some stuff in the package. But it's still +100mb. Is there any size limit or anything?
- There are no errors or anything in the deployment.

Well, that's mainly it. Not sure what you need more.

**Comment by olaj** [comment]
Seems to be some issue with the action. Just tried a deployment via Azure Devops instead and that worked fine. Probably some kind of issue with the zip (as the "signature mismatch" indicates). Would be nice if someone could take a look at it. Let me know if you need more info.

**Comment by olaj** [comment]
Anyone? It's been two week. Still the same error.

**Comment by AmrutaKawade** [comment]
Can you share debug logs for both Github action and AzureDevOps Task?
to get debug logs
Github action - add ACTIONS_STEP_DEBUG =  true in secrets and run workflow
AzureDevOps - add system.debug = true in variables and run pipeline

**Comment by AmrutaKawade** [comment]
closing this issue as no response from user. please feel free to reopen if issue still persist

**Comment by RobBowman** [comment]
I have the same issue - no answer on this thread?
