### ISSUE TITLE
Action is stuck

### ISSUE THREAD

**Issue by arti1zz** [Azure/webapps-deploy#260]
Hello! 

It seems there is a bug or I am missing something. I have a release script and today i switched action to run on my local pc(self-hosted). From now on, release script is stuck on deploy step.

How it looks: 

      name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.sjsg_FFFF }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
        
Full script: 

    name: Build and deploy .NET Core application to Web App sjsg
    on:
      push:
        branches:
        - develop
    env:
      AZURE_WEBAPP_NAME: sjsg
      AZURE_WEBAPP_PACKAGE_PATH: SJSG\published
      CONFIGURATION: Release
      DOTNET_CORE_VERSION: 6.0.x
      WORKING_DIRECTORY: SJSG
    jobs:
      build:
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v2
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
        - name: Restore
          run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
        - name: Build
          run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
        - name: Test
          run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
        - name: Publish
          run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
        - name: Deploy to Azure WebApp
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            publish-profile: ${{ secrets.sjsg_FFFF }}
            package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        - name: Publish Artifacts
          uses: actions/upload-artifact@v1.0.0
          with:
            name: webapp
            path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

**Comment by shpraka** [comment]
@arti1zz could you share at which step the action is stuck? If possible, could you share the logs of the action run?
