### ISSUE TITLE
"set-output command is deprecated" warning in workflow

### ISSUE THREAD

**Issue by duncansmart** [Azure/webapps-deploy#261]
Getting the following warning in my workflow using azure/webapps-deploy@v2:

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by BenjaminMichaelis** [comment]
I am seeing this as well with the same version

**Comment by vr1e** [comment]
Already mentioned here: #253

**Comment by BenjaminMichaelis** [comment]
Want to make sure this doesn't go idle

**Comment by shpraka** [comment]
We are updating the version in our next release, do expect it to fixed by 2nd week of December.

**Comment by shpraka** [comment]
We have updated the version and released it, please check and confirm if it's working fine now.

**Comment by BenjaminMichaelis** [comment]
Got lost in notifications, seems to be working thus far!
