### ISSUE TITLE
SCM_DO_BUILD_DURING_DEPLOYMENT Equivalent 

### ISSUE THREAD

**Issue by Fish1** [Azure/webapps-deploy#272]
When using the Azure VSCode extension, we are able to add a .deployment file to our project, with the following...
```
[config]
SCM_DO_BUILD_DURING_DEPLOYMENT=true
```

This allows us to install and build the app after uploading the source code, resulting in much faster deployments. Is there a way we can set this using the azure/webapps-deploy@v2 github action?

**Comment by shpraka** [comment]
Right now, we don't have that support on github action yet but you can set this app setting on azure portal. This(https://learn.microsoft.com/en-us/azure/app-service/configure-common?tabs=portal) has the steps to update the app settings.

**Comment by shpraka** [comment]
@Fish1 you could try this [github action](https://github.com/Azure/appservice-settings) to set the app setting. You can use multiple github actions in your workflow.

**Comment by shpraka** [comment]
@Fish1 Just checking if you were able to use the suggested step for your usecase.

**Comment by Fish1** [comment]
Sorry, we went down the path of your first suggestion by setting the option in azure directly.

Thanks for the help!

**Comment by shpraka** [comment]
Thanks @Fish1 for confirming, closing this issue.
