### ISSUE TITLE
azure django app deployment

### ISSUE THREAD

**Issue by Escsec** [Azure/webapps-deploy#278]
error 

<html>
<body>
<div class="mt-1 mb-3 px-3" style="box-sizing: border-box; margin-top: var(--base-size-4, 4px)  !important; margin-bottom: var(--base-size-16, 16px)  !important; padding-right: var(--base-size-16, 16px)  !important; padding-left: var(--base-size-16, 16px)  !important; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="mx-0 mx-md-1" style="box-sizing: border-box; margin-right: var(--base-size-4, 4px)  !important; margin-left: var(--base-size-4, 4px)  !important;"><h4 class="text-bold" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: var(--h4-size, 16px); font-weight: var(--base-text-weight-semibold, 600)  !important;">Annotations</h4><div class="color-fg-muted text-small" style="box-sizing: border-box; color: var(--color-fg-muted)  !important; font-size: var(--h6-size, 12px)  !important;">2 errors and 4 warnings</div></div></div>

deployFailed to deploy web package to App Service.
--
deployDeployment Failed with Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
buildNode.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v1, actions/upload-artifact@v2Show more
buildThe `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/Show more
deployNode.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/download-artifact@v2Show more
deployThe `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/Show more

</body>
</html>Annotations
2 errors and 4 warnings
[deploy](https://github.com/Escsec/HappyStudent/actions/runs/3715387769/jobs/6301201961#step:3:957)
Failed to deploy web package to App Service.
[deploy](https://github.com/Escsec/HappyStudent/actions/runs/3715387769/jobs/6301201961#step:3:958)
Deployment Failed with Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
[build](https://github.com/Escsec/HappyStudent/actions/runs/3715387769/jobs/6301201795)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v1, actions/upload-artifact@v2
[build](https://github.com/Escsec/HappyStudent/actions/runs/3715387769/jobs/6301201795#step:3:6)
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
[deploy](https://github.com/Escsec/HappyStudent/actions/runs/3715387769/jobs/6301201961)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/download-artifact@v2
[deploy](https://github.com/Escsec/HappyStudent/actions/runs/3715387769/jobs/6301201961#step:2:481)
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by Escsec** [comment]
my work flow


name: Build and deploy Python app to Azure Web App - happywebsite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'happywebsite'
          slot-name: 'Production'

**Comment by shpraka** [comment]
@Escsec Can you please with latest setup-python version? https://github.com/marketplace/actions/setup-python

We have already updated the action version to use Node16. 

If you're still facing issues, do share the sample app using so that we can repro and debug further.

**Comment by shpraka** [comment]
Closing the issue, please create new one or re-open in case of any further issues.
