### ISSUE TITLE
deploy: Failed to fetch credentials from Publish Profile.

### ISSUE THREAD

**Issue by varndellwagglebee** [Azure/webapps-deploy#279]
Getting the following errors on WebApps-Deploy:

Run azure/webapps-deploy@v2.2.5
Run azure/webapps-deploy@v2.2.5
  
(node:2066) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/runner/work/_actions/azure/webapps-deploy/v2.2.5/node_modules/actions-secret-parser/package.json' of 'lib/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
[xmldom warning]	attribute "glypheditorapi-staging" missed quot(")!! 
@#[line:1,col:14]
[xmldom warning]	attribute "-" missed value!! "-" instead2!! 
@#[line:1,col:14]
[xmldom error]	element parse error: Error: invalid attribute:- 
@#[line:1,col:14]
[xmldom warning]	attribute "glypheditorapi-staging" missed quot(")!! 
@#[line:1,col:515]
[xmldom warning]	attribute "-" missed value!! "-" instead2!! 
@#[line:1,col:515]
[xmldom error]	element parse error: Error: invalid attribute:- 
@#[line:1,col:515]
[xmldom warning]	attribute "glypheditorapi-staging" missed quot(")!! 
@#[line:1,col:1053]
[xmldom warning]	attribute "-" missed value!! "-" instead2!! 
@#[line:1,col:1053]
[xmldom error]	element parse error: Error: invalid attribute:- 
@#[line:1,col:1053]
Error: Failed to fetch credentials from Publish Profile. For more details on how to set publish profile credentials refer https://aka.ms/create-secrets-for-GitHub-workflows
Error: Deployment Failed with Error: Error: Publish profile does not contain kudu URL

`env:
  AZURE_WEBAPP_NAME: 'glypheditorapi'
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '7.0.x'                           # set this to the dot net core version to use
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  SOLUTION_NAME: 'GlyphEditor.sln'
  
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Master Configuration
        if: ${{env.BRANCH_NAME =='master' }}
        run: |
           echo "BUILD_CONFIGURATION=Release" >> $GITHUB_ENV
           echo "VERSION_SUFFIX=" >> $GITHUB_ENV 
           echo "PUBLISH_PROFILE= ${{ secrets.API_PUBLISH_PROFILE_PROD}}" >> $GITHUB_ENV 
           echo "SLOT='production'" >> $GITHUB_ENV 
           
      - name: Debug Configuration
        if: ${{ env.BRANCH_NAME == 'develop'}}
        run: |
            echo "BUILD_CONFIGURATION=Debug" >> $GITHUB_ENV
            echo "VERSION_SUFFIX=develop.$(date +'%y%m%d%H%M%S')" >> $GITHUB_ENV
            echo "PUBLISH_PROFILE= ${{ secrets.API_PUBLISH_PROFILE_STAGING}}" >>$GITHUB_ENV 
            echo "SLOT='staging'" >>$GITHUB_ENV
            
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        working-directory: src/api/GlyphEditor
        run:  dotnet build ${{ env.SOLUTION_NAME }} --configuration ${{env.BUILD_CONFIGURATION}}
      
      - name: Test
        working-directory: src/api/GlyphEditor
        run: dotnet test ${{ env.SOLUTION_NAME }} --no-restore

      - name: dotnet publish
        working-directory: src/api/GlyphEditor
        run: dotnet publish ${{ env.SOLUTION_NAME }} --configuration ${{env.BUILD_CONFIGURATION}} -o ${{env.DOTNET_ROOT}}/glphyeditor
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2.2.5
        with:
            app-name: '${{ env.AZURE_WEBAPP_NAME }}'
            slot-name: '${{env.SLOT}}'
            publish-profile: ${{ env.PUBLISH_PROFILE }}
            package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/glphyeditor
`

I did confirm my publish profile is from the staging slot.

**Comment by shpraka** [comment]
@varndellwagglebee Can you please check if PUBLISH_PROFILE added in your secret is same as downloaded from the "Publish Profile" on Azure Portal? While added as secret please ensure it's not modified after downloaded.

**Comment by varndellwagglebee** [comment]
You can't check because it's a secret, but I did download the publish profile and copied the entire thing into the secret.  I tried this several times.

**Comment by shpraka** [comment]
@varndellwagglebee Since we have multiple entries in publish profile with double quotes, the code block to set env variable should use single quotes so that full published profile is set. 
Change should be like below"

**echo "PUBLISH_PROFILE= ${{ secrets.API_PUBLISH_PROFILE_PROD}}" >> $GITHUB_ENV** -> echo 'PUBLISH_PROFILE= ${{ secrets.API_PUBLISH_PROFILE_PROD}}' >> $GITHUB_ENV 

Do let us know if you still face issue.

**Comment by shpraka** [comment]
Closing this issue, please re-open or create new issue if encounters any issue.
