### ISSUE TITLE
Deployment Failed with Error: Error: Publish profile does not contain kudu URL

### ISSUE THREAD

**Issue by chandan-g-bhagat** [Azure/webapps-deploy#28]
![image](https://user-images.githubusercontent.com/6848264/78800829-a1f1d280-79db-11ea-9b09-3f01a5d1ebbc.png)

Failed to fetch credentials from Publish Profile. For more details on how to set publish profile credentials refer https://aka.ms/create-secrets-for-GitHub-workflows
Deployment Failed with Error: Error: Publish profile does not contain kudu URL
On deployment I got this error. I have added the entire content of publish setting file. Any possible reason for this?

**Comment by RoopeshNair** [comment]
Do you have `publishUrl` attribute in your publishprofile file?

**Comment by lcm98** [comment]
Having the same issue, our credentials were set up automatically via our App Center's Deployment center, after that didn't work we tried going manually via the error link (https://aka.ms/create-secrets-for-GitHub-workflows).

Is there any examples of what the secret value (publish profile) should look like?

**Comment by chandan-g-bhagat** [comment]
> Do you have `publishUrl` attribute in your publishprofile file? 

Actually I fixed it, There was issue in publish url. It didn't have scm in the url.

**Comment by chandan-g-bhagat** [comment]
> Having the same issue, our credentials were set up automatically via our App Center's Deployment center, after that didn't work we tried going manually via the error link (https://aka.ms/create-secrets-for-GitHub-workflows).
> 
> Is there any examples of what the secret value (publish profile) should look like?

Actually when you open the publish profile in any text editor, you need to add entire content of that file name as secret. I think to be precise, rhat should contain the publish setting of type web deploy with the publish url as https://<example>.scm.azurewebsites.net

**Comment by lcm98** [comment]
> > Having the same issue, our credentials were set up automatically via our App Center's Deployment center, after that didn't work we tried going manually via the error link (https://aka.ms/create-secrets-for-GitHub-workflows).
> > Is there any examples of what the secret value (publish profile) should look like?
> 
> @lcm98
> Actually when you open the publish profile in any text editor, you need to add entire content of that file name as secret. I think to be precise, rhat should contain the publish setting of type web deploy with the publish url as
> https://<-example->.scm.azurewebsites.net

@chandan-g-bhagat 
This is the Publish Profile I get from Azure (sensitive data removed)

```xml
<publishData>
     <publishProfile profileName="[app-name] - Web Deploy" publishMethod="MSDeploy" publishUrl="waws-prod.publish.azurewebsites.windows.net:443" msdeploySite="[app-name]" userName="$[app-name]" userPWD="***" destinationAppUrl="http://[app-name].azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites">
        <databases />
    </publishProfile>
    <publishProfile profileName="[app-name] - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="[app-name]\$[app-name]" userPWD="***" destinationAppUrl="http://[app-name].azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites">
        <databases />
    </publishProfile>
    <publishProfile profileName="[app-name] - ReadOnly - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="[app-name]\$[app-name]" userPWD="***" destinationAppUrl="http://[app-name].azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites">
        <databases />
    </publishProfile>
</publishData>
```

Do I include everything, the <publishData> tags as well as all 3 publish profiles?

So I need to change the publishURL that they provide? Will get back to you with how that works.

**Comment by chandan-g-bhagat** [comment]
> > > Having the same issue, our credentials were set up automatically via our App Center's Deployment center, after that didn't work we tried going manually via the error link (https://aka.ms/create-secrets-for-GitHub-workflows).
> > > Is there any examples of what the secret value (publish profile) should look like?
> > 
> > @lcm98
> > Actually when you open the publish profile in any text editor, you need to add entire content of that file name as secret. I think to be precise, rhat should contain the publish setting of type web deploy with the publish url as
> > https://<-example->.scm.azurewebsites.net
> 
> @chandan-g-bhagat 
> This is the Publish Profile I get from Azure (sensitive data removed)
> 
> ```xml
> <publishData>
>      <publishProfile profileName="[app-name] - Web Deploy" publishMethod="MSDeploy" publishUrl="waws-prod.publish.azurewebsites.windows.net:443" msdeploySite="[app-name]" userName="$[app-name]" userPWD="***" destinationAppUrl="http://[app-name].azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites">
>         <databases />
>     </publishProfile>
>     <publishProfile profileName="[app-name] - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="[app-name]\$[app-name]" userPWD="***" destinationAppUrl="http://[app-name].azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites">
>         <databases />
>     </publishProfile>
>     <publishProfile profileName="[app-name] - ReadOnly - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="[app-name]\$[app-name]" userPWD="***" destinationAppUrl="http://[app-name].azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites">
>         <databases />
>     </publishProfile>
> </publishData>
> ```
> 
> Do I include everything, the <publishData> tags as well as all 3 publish profiles?
> 
> So I need to change the publishURL that they provide? Will get back to you with how that works.


@lcm98 
```
<publishData>
     <publishProfile profileName="[app-name] - Web Deploy" publishMethod="MSDeploy" publishUrl="waws-prod.publish.azurewebsites.windows.net:443" msdeploySite="[app-name]" userName="$[app-name]" userPWD="***" destinationAppUrl="http://[app-name].azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites">
        <databases />
  </publishProfile>
```

I had the same issue in this publishurl, use 
[app-name].scm.azurewebsites.net instead of 
waws-prod.publish.azurewebsites.windows.net

**Comment by lcm98** [comment]
@chandan-g-bhagat Ok I'll try that, should I include the 2 FTP publish profiles or remove them, or does it not matter?

**Comment by chandan-g-bhagat** [comment]
> @chandan-g-bhagat Ok I'll try that, should I include the 2 FTP publish profiles or remove them, or does it not matter?

@lcm98 I think it won't be any issues removing them. However, I didn't removed it. You can try it. But I can assure that ot wouldn't affect removing those 2 ftp. You need msdeploy though.

**Comment by lcm98** [comment]
Yes that got it to work, thank you very much, was a life saver.

On a side note, we setup the publishing profile for another app service right after spending hours on this one, and it actually created the publishURL correctly, so we didn't have to change anything, which is kind of... funny?

**Comment by chandan-g-bhagat** [comment]
> Yes that got it to work, thank you very much, was a life saver.
> 
> On a side note, we setup the publishing profile for another app service right after spending hours on this one, and it actually created the publishURL correctly, so we didn't have to change anything, which is kind of... funny?

@lcm98 glad it worked. It took me a working day to figure this out. There might be some issues while fetching the publish profile. I didn't find any setting to generate scm url in publish profile.! Good day!

**Comment by rtheil** [comment]
I'm going to add to this just to verify that I had the same issue. I created a node app and had Azure create the pipeline for me on github. It did this successfully. Then I created a .Net core API and tried to publish using the EXACT same method. It failed. 

To fix:
Downloaded the publish profile from azure, edited the file, looked for publishUrl="waws-prod-bay-143.publish.azurewebsites.windows.net:443" and replaced it with publishUrl="[my-app-name].scm.azurewebsites.net:443" then copied the entire contents of the file and updated the secret stored in my github repository. Everything started working. 

Also verified that in the publish config file for my Node app that the publishUrl was indeed pointing to scm.azurewebsites.net.

It's obvious this is a bug with the Github deployment in Azure, and specific to .Net Core (and probably other) apps.

**Comment by Joren-Thijs** [comment]
> 
> 
> I'm going to add to this just to verify that I had the same issue. I created a node app and had Azure create the pipeline for me on github. It did this successfully. Then I created a .Net core API and tried to publish using the EXACT same method. It failed with error:
> `##[error]Failed to fetch credentials from Publish Profile. For more details on how to set publish profile credentials refer https://aka.ms/create-secrets-for-GitHub-workflows ##[error]Deployment Failed with Error: Error: Publish profile does not contain kudu URL`
> 
> To fix:
> Downloaded the publish profile from azure, edited the file, looked for publishUrl="waws-prod-bay-143.publish.azurewebsites.windows.net:443" and replaced it with publishUrl="[my-app-name].scm.azurewebsites.net:443" then copied the entire contents of the file and updated the secret stored in my github repository. Everything started working.
> 
> Also verified that in the publish config file for my Node app that the publishUrl was indeed pointing to scm.azurewebsites.net.
> 
> It's obvious this is a bug with the Github deployment in Azure, and specific to .Net Core (and probably other) apps.

Can confirm had the same issue, still on 14/10/2020. Replacing the URL fixed it👍

**Comment by kokuljose** [comment]
A solution is described [here](https://stackoverflow.com/questions/64376240/github-action-for-azure-python-webapp-failed-to-fetch-credentials-from-publish/64376536#64376536).

**Comment by Jriles** [comment]
Getting this bug with python 3.8 first deploy and successive deploys

**Comment by Jriles** [comment]
Also the fix works but you have to put your app name in for the [app-name] bit. Maybe this is obvious but I wasn't sure.

**Comment by olli1337** [comment]
I can confirm that this URL issue still exists. Also be careful to check the app name to match the app service name that you created in Azure.

**Comment by erfannariman** [comment]
Why is this issue closed? This is still a problem, can this be re-opened?

**Comment by pietelite** [comment]
It is solved, but the answer is kinda scattered around on this thread. [I made a StackOverflow post about it](https://stackoverflow.com/questions/64518967/azure-github-app-deployment-error-publish-profile-does-not-contain-kudu-url/64518968#64518968) to help people figure it out.

**Comment by chuanqisun** [comment]
Please consider re-open the issue @chandan-g-bhagat . The workaround is good but many users will hit the same problem and waste their time. Please fix update either Azure portal or update the Github Actions to ensure the default publish profile work out-of-the-box.

**Comment by rtheil** [comment]
My understanding of this issue is that it is not an issue of webapps-deploy, and thus not relevant here. It seems to be an Azure portal bug, which is incorrectly generating the script that calls webapps-deploy for certain app types, specifically .Net Core apps. I do not believe webapps-deploy has anything to do with generation of the script within Azure.

**Comment by Jriles** [comment]
Its not just .Net core, like I stated above. And if it isn't an issue with webapps-deploy, even if this occurs during app deployment, shouldn't there be a new issue opened and a link to it here maybe?

**Comment by erfannariman** [comment]
For those who it might interest, I've opened an issue on [docs.microsoft.com](https://docs.microsoft.com/en-us/answers/questions/137869/publish-profile-publishurl-needs-to-be-adjusted-af.html) as well.

**Comment by erfannariman** [comment]
Here is a temporary solution:
1. Go to your function app and to configuration:
![image](https://user-images.githubusercontent.com/34067903/97820167-232cf180-1cad-11eb-87f1-f2bb74d5f2fa.png)

2. Press "New applications setting":
![image](https://user-images.githubusercontent.com/34067903/97820199-54a5bd00-1cad-11eb-99cf-a5da2bb2d510.png)

3. Then add the following:
![image](https://user-images.githubusercontent.com/34067903/97820226-6e470480-1cad-11eb-884a-5b8143e2683f.png)

4. Redownload "Publish Profile", then the `publishUrl` will be correct set to scm.

**Comment by dtmzr** [comment]
@erfannariman can confirm that this works and in my opinion, is the best / most consistent workaround. Thanks a lot for putting effort into this 🙏

**Comment by Ankuraxz** [comment]
set `WEBSITE_WEBDEPLOY_USE_SCM = true` in application settings
Disconnect GitHub & delete workflow file
Reconnect & Redeploy
