### ISSUE TITLE
Deploying using v2 shows warning "[DEP0128] DeprecationWarning: Invalid 'main' field in ..."

### ISSUE THREAD

**Issue by markwhitaker** [Azure/webapps-deploy#282]
Deploying with `uses: azure/webapps-deploy@v2` shows a deprecation warning as follows:

> (node:1643) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/runner/work/_actions/azure/webapps-deploy/v2/node_modules/actions-secret-parser/package.json' of 'lib/index.js'. Please either fix that or report it to the module author

**Comment by shpraka** [comment]
This is fixed as part of #280, will be rolled out in next release.

**Comment by oleksandrfurmanov** [comment]
> This is fixed as part of #280, will be rolled out in next release.

Had the same issue, when it will be rolled out?

**Comment by shpraka** [comment]
It will be rolled out by Feb 2nd Week.

**Comment by aaronjones1** [comment]
@shpraka Is there a workaround for this in the meantime, or is it just not possible to deploy until then?

**Comment by shpraka** [comment]
@aaronjones1 Unfortunately we couldn't find any workaround yet.

**Comment by shpraka** [comment]
@aaronjones1 We have done the rollout, it should go away now.
