### ISSUE TITLE
Deprecation warning in actions_secrets_parser

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [Azure/webapps-deploy#286]
When running a deployment through GitHub actions to my app service, it shows the following warning in the logs:

(node:1733) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/runner/work/_actions/azure/webapps-deploy/v2/node_modules/actions-secret-parser/package.json' of 'lib/index.js'. Please either fix that or report it to the module author

This has been logged for future fixing.

**Comment by shpraka** [comment]
It has been fixed as part of #280  and will go in next rollout which will be 2nd week of February.
