### ISSUE TITLE
Long commit message on zipdeploy not being trimmed enough

### ISSUE THREAD

**Issue by IGx89** [Azure/webapps-deploy#288]
#271 added a length limit to the commit message, but it's still too short. I experimentally discovered that Kudu gives a 404 response for any URLs that have a query string longer than 2048 characters.  The 7000 limit added in #271 is thus still much too long, it needs to be short enough that it, along with the rest of the query parameters and encoded JSON object, add up to less than 2048 characters. Guessing it should be less than 1000, since the trimming is done before the URL encoding which could more than double the effective length (" " becomes "%20", etc.).

**Comment by kumaraksh1** [comment]
@IGx89 are you facing any issue while deploying the changes ??
Like we tested it multiple times and it worked. But happy to work on it again if you are still facing any issues.

**Comment by IGx89** [comment]
Yep, we discovered this issue when doing a deployment last week. Zip deploy URL had 2572 characters, which was too long for Kudu. I experimented and dug through the code to determine the numbers in my description above.

What scenarios did you test? Do my findings above (Kudu's query string limit is 2048 characters and this action only trims commit messages longer than 7000 characters) seem accurate to you?

**Comment by shpraka** [comment]
@IGx89  I tried this and it's working with current constraint on the 7000. Do check the logs here: https://github.com/shpraka/NodeJsAppVer18/actions/runs/4262080360/jobs/7417199825. 

Also can you please share the action run logs where we can see the full URI and check the length, it will help us debug further?

**Comment by shpraka** [comment]
@IGx89 The app I was using for above example was on Linux.

**Comment by IGx89** [comment]
Thanks! Wouldn't be surprised at all if a web server on Linux allowed longer query string params than a Windows web server. I see a PR got merged that should fix this issue, thank you! I'll close this now, in anticipation of a new release coming soon, and will re-open if I encounter the issue again.

**Comment by shpraka** [comment]
@IGx89 We will be releasing the change soon, in a couple of weeks.
