### ISSUE TITLE
Issue failing deployment with Publish profile

### ISSUE THREAD

**Issue by santhoshb-msft** [Azure/webapps-deploy#289]
Deployment failing and asking for az ad login, even when doing a publish profile deployment.

Same file didnt have problems deploying in a different repo but failing in another repo.

![image](https://user-images.githubusercontent.com/63607175/215392396-b066cdec-20d2-429f-b86c-528b8af524ee.png)

**Comment by santhoshb-msft** [comment]
Hi @shpraka

https://github.com/santhoshb-msft/Commercial-Marketplace-SaaS-Accelerator/blob/sb-uitest/.github/workflows/cicd.yml

Works in my fokred repo but fails on the main repo PR here - https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/pull/431.

**Comment by shpraka** [comment]
Can you please check if publish profile secret key is set correctly? The above error can only happen if the secret is not present when publish-profile is chosen.

**Comment by shpraka** [comment]
Closing the issue.
