### ISSUE TITLE
azure/webapps-deploy@v2 | Deprecated warnings. 

### ISSUE THREAD

**Issue by surenderssm** [Azure/webapps-deploy#291]
For dotnet 7 app GitHub action deploy on Linux Web app service, following error has been observed.

`(node:1612) [DEP012[8](https://github.com/surenderssm/hello-dotent-7-linuxapp/actions/runs/4085228593/jobs/7042931866#step:3:9)] DeprecationWarning: Invalid 'main' field in '/home/runner/work/_actions/azure/webapps-deploy/v2/node_modules/actions-secret-parser/package.json' of 'lib/index.js'. Please either fix that or report it to the module author`

For run details : https://github.com/surenderssm/hello-dotent-7-linuxapp/actions/runs/4085228593/jobs/7042931866
![image](https://user-images.githubusercontent.com/12485087/216636931-99b0e229-406e-44e9-a746-22da40f8be2a.png)

**Comment by surenderssm** [comment]
Similar observation.

![image](https://user-images.githubusercontent.com/12485087/216638545-2228ab63-3dbb-4c34-8469-ca869b693f02.png)

**Comment by shpraka** [comment]
This has been fixed. We would be rolling out the fix in next release.

**Comment by surenderssm** [comment]
https://github.com/Azure/webapps-deploy/pull/280

**Comment by shpraka** [comment]
Rollout is done. Closing the issue.
