### ISSUE TITLE
Error on deploying to Azure app service

### ISSUE THREAD

**Issue by will300** [Azure/webapps-deploy#292]
Hi,
I am using the webapps-deploy v2 github action to deploy artifact to azure app service, and getting the following error -

Step Details –

Run azure/webapps-deploy@v2
with:
app-name: functionapp
publish-profile: ***
package: bin

Error Message -

Copying files to destination directory '/home/site/wwwroot'...
Done in 4 sec(s).

Removing existing manifest file
Creating a manifest file...
Manifest file created.

Done in 29 sec(s).
Running post deployment command(s)...

Generating summary of Oryx build
Deployment Log file does not exist in /tmp/oryx-build.log
The logfile at /tmp/oryx-build.log is empty. Unable to fetch the summary of build
Triggering recycle (preview mode disabled).
Linux Consumption plan has a 1.5 GB memory limit on a remote build container.
To check our service limit, please visit https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#service-limits
Writing the artifacts to a squashfs file
Parallel mksquashfs: Using 1 processor
Creating 4.0 filesystem on /home/site/artifacts/functionappartifact.squashfs, block size [131](https://github.com/AXA-Venture-Partners/Anabot/actions/runs/4105811653/jobs/7083194888#step:7:132)072.

[=============================================================/] 6677/6677 100%

Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
	compressed data, compressed metadata, compressed fragments, compressed xattrs
	duplicates are removed
Filesystem size 42229.82 Kbytes (41.24 Mbytes)
	30.36% of uncompressed filesystem size ([139](https://github.com/AXA-Venture-Partners/Anabot/actions/runs/4105811653/jobs/7083194888#step:7:140)101.05 Kbytes)
Inode table size 65665 bytes (64.13 Kbytes)
	28.88% of uncompressed inode table size (227400 bytes)
Directory table size 66071 bytes (64.52 Kbytes)
	35.44% of uncompressed directory table size (186420 bytes)
Number of duplicate files found 456
Number of inodes 7018
Number of files 6214
Number of fragments 507
Number of symbolic links  0
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 804
Number of ids (unique uids + gids) 1
Number of uids 1
	root (0)
Number of gids 1
	root (0)
Creating placeholder blob for linux consumption function app...
Malformed SCM_RUN_FROM_PACKAGE when uploading built content.

Generating summary of Oryx build
Deployment Log file does not exist in /tmp/oryx-build.log
The logfile at /tmp/oryx-build.log is empty. Unable to fetch the summary of build
Deployment Failed. deployer = GITHUB_ZIP_DEPLOY deploymentPath = Functions App ZipDeploy. Extract zip. Remote build.
Error: Failed to deploy web package to App Service.
Error: Deployment Failed with Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
App Service Application URL: https://axavp.azurewebsites.net/

**Comment by shpraka** [comment]
@will300 is the app still active? I am not able to see the app. Could you share some details on app for us to debug further?

**Comment by will300** [comment]
The app is active and running on Azure. Some details are as follows:

Location: West Europe
Operating System: Linux
Runtime Version: 4.15.1.1
Status: Ready
Zone Redundant: Disabled
ENABLE_ORYX_BUILD: 1
FUNCTIONS_EXTENSION_VERSION: ~4
FUNCTIONS_WORKER_RUNTIME: python
SCM_DO_BUILD_DURING_DEPLOYMENT: 1
App Service authentication: Enabled
Restrict access: Require authentication
Unauthenticated requests: Return HTTP 401 Unauthorized
Token store: Enabled

I can provide further specific details if needed.
And the repo I'm trying to deploy has roughly the following file structure:

├── .github
│   ├── workflows
      │   ├── config.yml
├── bin
│   ├── dir1
      │   ├── file1.py
      │   └── file2.py
      │   └── __init__.py
│   ├── dir2
      │   ├── file1.py
      │   └── file2.py
      │   └── __init__.py
│   ├── __init__.py
├── host.json
├── local.settings.json
├── requirements.txt
├── otherfile1
└── otherfile2

**Comment by shpraka** [comment]
Seems like you're using functionapp. There is a different action for [azure functions](https://github.com/Azure/functions-action). 
Can you try this workflow: https://github.com/Azure/actions-workflow-samples/blob/master/FunctionApp/linux-python-functionapp-on-azure.yml?

**Comment by will300** [comment]
I've tried this workflow as well but it gives exactly the same error

**Comment by shpraka** [comment]
Azure Function should be correct place to troubleshoot. Adding the contributor @fsschmitt @patelchandni to take a look on this.

**Comment by will300** [comment]
Thank you. I've looked at that repo but it doesn't seem as active for issues. Is there anywhere else you would recommend looking for help troubleshooting in the meantime?

**Comment by shpraka** [comment]
Since we use zip deploy in our github action, we advise all the webapps deploy user to [enable run from package](https://learn.microsoft.com/en-us/azure/app-service/deploy-run-package#enable-running-from-package), can you check if enabling run from package helps?

**Comment by will300** [comment]
I've tried setting WEBSITE_RUN_FROM_PACKAGE = 1 as it says in the link but now get an error slightly earlier on

![image](https://user-images.githubusercontent.com/30575955/218117086-d417aaaa-5cd2-428c-82e4-82292429b492.png)

**Comment by kamperiadis** [comment]
@will300 Looks like you are using `webapps-deploy`. Can you please try using `functions-action`? `functions-action` is the recommended action.

**Comment by kamperiadis** [comment]
@will300 Looks like there is an AzureWebJobsStorage warning indicating that the app setting is missing. Can you please add that app setting?

**Comment by kamperiadis** [comment]
Here is some documentation you can reference for that app setting: https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#azurewebjobsstorage

**Comment by kamperiadis** [comment]
@will300  You are using linux consumption, and I see you have `WEBSITE_RUN_FROM_PACKAGE` set to 1. Run from package is not available for linux consumption. For linux consumption, please set `WEBSITE_RUN_FROM_PACKAGE` to 0 (or do not set it). And set `SCM_DO_BUILD_DURING_DEPLOYMENT` to true (https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#scm_do_build_during_deployment)

**Comment by kamperiadis** [comment]
@will300 Here is some useful documentation in case it helps:
https://learn.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#enable-functions-to-run-from-a-package
https://learn.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#general-considerations

**Comment by kamperiadis** [comment]
Just to clarify, please note that the solution I proposed is specifically for _function app deployments_. WEBSITE_RUN_FROM_PACKAGE =1 is what is suggested for _web app deployments_.

**Comment by shpraka** [comment]
@will300 were you able to resolve the issue by steps shared by @kamperiadis?

**Comment by will300** [comment]
Not yet unfortunately, I have tried setting the AzureWebJobsStorage and no longer receive the warning, and also the WEBSITE_RUN_FROM_PACKAGE variable, but other than that the error is still the same.

**Comment by kamperiadis** [comment]
@will300 The issue might be related to something else. Since you have had two different error logs, can you please clarify for me which error you are seeing now? Can you please share the latest logs from the GitHub repo by clicking on "Actions" tab > "All Workflows" > click on failed run > copy the logs under "Run Azure Functions Action". Can you please also share your deployment pipeline in yaml?

**Comment by shpraka** [comment]
@will300 can you please share the logs and workflow yaml which @kamperiadis asked above?

**Comment by shpraka** [comment]
@will300 Reminding for the same again.

**Comment by shpraka** [comment]
@will300 Waiting for the revert. will close this item by 28th Feb.

**Comment by shpraka** [comment]
Closing this issue because of no response. Feel free to re-open or create new one.
