### ISSUE TITLE
Custom Kudu Deployment logging

### ISSUE THREAD

**Issue by aparry1** [Azure/webapps-deploy#294]
Would it be possible to setup a custom key + value to append to the Kudu Deployment logging, that way we could add additional information to the logged payload.  e.g. github.triggering_actor, to give an additional log of whom triggered a run

I believe this may be done through the WebAppDeploymentProvider.js, and actionparameters.js, perhaps in a similar fashion to the commitMessage action parameter?

**Comment by shpraka** [comment]
@aparry1 what's the objective of the custom key + value? Is it to log the person who is triggering the deployment?
