### ISSUE TITLE
Github Action stopped working

### ISSUE THREAD

**Issue by d3-konstantin-zaigraev** [Azure/webapps-deploy#319]
Today morning from CI/CD pipeline I got an error on init state (_set up job_) for windows-latest Github Runner:

```
Download action repository 'azure/webapps-deploy@v2' (SHA:4ed4d429f1f77116d756b900be4070e3ae9bb76f)
Error: The file 'D:\a\_actions\_temp_82daf5a5-77cf-4717-9834-dc92afed4c79\_staging\Azure-webapps-deploy-4ed4d42\node_modules\querystring\
Readme.md' already exists.
```
Does somebody else has same issue?

**Comment by neoscie** [comment]
Yes, same here.

We changed from `azure/webapps-deploy@v2` to `azure/webapps-deploy@v2.2.6` until it's fixed.

**Comment by martincostello** [comment]
+1 - this has broken all my Azure App Service deployments.

[Example failed deployment](https://github.com/martincostello/costellobot/actions/runs/4626821555/jobs/8184532448#step:1:37)

**Comment by martincostello** [comment]
Please move the `v2` tag back to 2087f42f7c9306a8d6d45d733e45d2048a9a735a until this issue is resolved.

**Comment by henriksen** [comment]
Seems to be a problem with the Querystring module having two Readme.md files, but with different casing: 
<img width="127" alt="image" src="https://user-images.githubusercontent.com/121837/230326239-c8d052a4-9449-4797-a53a-32d0ba55a57a.png">

**Comment by shpraka** [comment]
We are looking into it.

**Comment by VasilisZenergi** [comment]
I can reaffirm this issue. We had this, since this morning (UK time). 
Issue is with duplicate README files here: \Azure-webapps-deploy-4ed4d42\node_modules\querystring

**Comment by LarsHoldgaard** [comment]
I've temp solved problems in our end by changing from:
`uses: azure/webapps-deploy@v2`

To:
`uses: azure/webapps-deploy@v2.2.6`

As this version works.

I'll swop back after fix :-) 

Thanks for looking into this a nice easter Thursday!

**Comment by martincostello** [comment]
`v2.2.9` and the retagged `v2` now seem to be working.

**Comment by kumaraksh1** [comment]
We have triggered one more release after updating the node modules.
Can you please check and update the thread ??

**Comment by shpraka** [comment]
Thanks for the confirmation, I am closing this issue now.
