### ISSUE TITLE
some files in node_modules are not updated

### ISSUE THREAD

**Issue by Frank-Krick** [Azure/webapps-deploy#32]
My deployment of a typescript/node based web app does not update files in node_modules.

If I delete the offending file, it will be updated with the new version on the next deployment.

**Comment by AmrutaKawade** [comment]
We use kudu REST api for deployment. as per kudu api documentation is known issue .

[Issues and investigation](https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file-or-url#issues-and-investigation)
Zip deploy does not update node module files for NPM 5.6 and later
See https://github.com/projectkudu/kudu/issues/2917 and https://github.com/npm/npm/issues/20439. This affects the default zipdeploy behavior where it is optimized to only copy files that are changed. To workaround the issue, do set appSettings SCM_ZIPDEPLOY_DONOT_PRESERVE_FILETIME=1. Zipdeploy files will always be updated and, as a result, overwriting the existing ones regardless of change.

**Comment by AmrutaKawade** [comment]
Please do try above workround. closing this issue. feel free to reopen if its not resolved
