### ISSUE TITLE
It isn't possible to deploy to a virtual application

### ISSUE THREAD

**Issue by snorydr** [Azure/webapps-deploy#33]
Azure Pipelines App Service Deploy tasks have the "VirtualApplication" input to allow deployment to a virtual application within the main App Service. There is no equivalent in this Action. Is this by design?

**Comment by eaarora-ms** [comment]
@snorydr  Yes for now we do not have virtual application deployment in Actions. We will be adding it on a later stage.

**Comment by snaoc** [comment]
Any news on this? Am in need for it (and I figure most SPA <-> API devs not liking pre-flights are...) as actions can automate every workflow very nicely, ecxept for this one. Thanks!

**Comment by valdesrenier1** [comment]
This will be a very helpful feature to include.
