### ISSUE TITLE
Failed to deploy web package to App Service SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by VasilisZenergi** [Azure/webapps-deploy#332]
We have our PROD CI workflow that worked fine up and till now. We are getting the error below. There is no clear clue on what may  be causing the issue. The same work flow on the DEV branch works, with the only difference been the AZURE_WEBAPP_PUBLISH_PROFILE and the fact that the PROD also uses a AZURE_WEBAPP_SLOT_NAME.

Run azure/webapps-deploy@v2
  with:
    app-name: XXXX
    package: XXXX/publish
    publish-profile: ***
    slot-name: stage
  env:
    AZURE_WEBAPP_NAME: XXXX
    AZURE_WEBAPP_SLOT_NAME: stage
    AZURE_WEBAPP_PACKAGE_PATH: XXXX/publish
    AZURE_WEBAPP_PUBLISH_PROFILE: ***
    CONFIGURATION: Release
    DOTNET_CORE_VERSION: 7.0.x
    WORKING_DIRECTORY: XXXX
    DOTNET_ROOT: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet
    BUILD_NUMBER: 213
Package deployment using ZIP Deploy initiated.
Updating submodules.
Preparing deployment for commit id 'f370fab734'.
Generating deployment script.
Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "C:\local\Temp\zipdeploy\extracted" -o "C:\home\site\deployments\tools" --basic --sitePath "C:\local\Temp\zipdeploy\extracted"'.
C:\PROGRA~2\SITEEX~1\NODEAP~1\296456~1.8\nodejs\build\src\Loader.js:153
                ...StatusLogger.DEFAULT_STATUS,
                ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at module.js:669:12
    at Array.forEach (native)
C:\PROGRA~2\SITEEX~1\NODEAP~1\296456~1.8\nodejs\build\src\Loader.js:153\r\n                ...StatusLogger.DEFAULT_STATUS,\r\n                ^^^\r\n\r\nSyntaxError: Unexpected token ...\r\n    at createScript (vm.js:56:10)\r\n    at Object.runInThisContext (vm.js:97:10)\r\n    at Module._compile (module.js:542:28)\r\n    at Object.Module._extensions..js (module.js:579:10)\r\n    at Module.load (module.js:487:32)\r\n    at tryModuleLoad (module.js:446:12)\r\n    at Function.Module._load (module.js:438:3)\r\n    at Module.require (module.js:497:17)\r\n    at module.js:669:12\r\n    at Array.forEach (native)\r\nC:\Program Files (x86)\SiteExtensions\Kudu\100.50331.6204\bin\Scripts\starter.cmd "C:\Program Files (x86)\SiteExtensions\Kudu\100.50331.6204\bin\node_modules\.bin\kuduscript.cmd" -y --no-dot-deployment -r "C:\local\Temp\zipdeploy\extracted" -o "C:\home\site\deployments\tools" --basic --sitePath "C:\local\Temp\zipdeploy\extracted"
Deployment Failed.
Error: Failed to deploy web package to App Service.
Error: Deployment Failed, Package deployment using ZIP Deploy failed. Refer logs for more details.
App Service Application URL: XXXX

The content of the workflow is below:

name: Build and deploy .NET Core app to Windows WebApp XXXX
on:
  push:
    branches:
    - Production
env:
  AZURE_WEBAPP_NAME: XXXX
  AZURE_WEBAPP_SLOT_NAME: stage
  AZURE_WEBAPP_PACKAGE_PATH: XXXX/publish
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.XXXX }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 7.0.x
  WORKING_DIRECTORY: XXXX
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Read Version File Content
      id: json_properties
      uses: ActionsTools/read-json-action@main
      with:
        file_path: "./VERSION.json"
    - name: Version File Content
      run: echo ${{ steps.json_properties.outputs.version }}
    - name: Generate Build Number
      id: buildnumber
      uses: onyxmueller/build-tag-number@v1
      with:
        token: ${{ secrets.github_token }}        
    - name: Print New Build Number
      run: echo "Build number is ${{steps.buildnumber.outputs.build_number}}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore -property:Version=${{ steps.json_properties.outputs.version }}.${{ steps.buildnumber.outputs.build_number }}
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
        slot-name: ${{ env.AZURE_WEBAPP_SLOT_NAME }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

**Comment by VasilisZenergi** [comment]
Closed as duplicate.

**Comment by IronSean** [comment]
@VasilisZenergi Closed as a duplicate of which issue? 

Looks like closed as a duplicate of #323

**Comment by VasilisZenergi** [comment]
Apologies. Yes it was duplicate to [323](https://github.com/Azure/webapps-deploy/issues/323)
