### ISSUE TITLE
Enabling ACTIONS_STEP_DEBUG causes webapps-deploy to leak Web App ENV vars to the log

### ISSUE THREAD

**Issue by NoCopy** [Azure/webapps-deploy#334]
As per the title. Turning Debug on should not leak the web application settings into the github log. 

A helpful but not necessary feature would be to log the NAMES of the ENV vars but redact the contents.
Something like: USES_ENV=[VAR1,VAR2,VAR3]

So you can spot a missing var if required.

**Comment by NoCopy** [comment]
@shpraka Well I deleted my logs for obvious reasons and reset any vars that got leaked so I would rather not go through that again but you should be able to test this on any blank Web App. 

And yes, I am specifically talking about the Environment Vars in the App Service App Settings. 

In the debug log one of the first things it does when triggering the deploy is it spits out the App Settings to the console. So anything in Configuration > Application Settings. 

I didn't really notice if both the Application Settings and Connection Strings are both getting leaked but App settings are for sure.

**Comment by sgollapudi77** [comment]
@shpraka @NoCopy , I tried to reproduce this. I can see values of App settings in the console logs but not the connection strings.
