### ISSUE TITLE
Reopen #154 : Deploy to custom folder. 

### ISSUE THREAD

**Issue by NoCopy** [Azure/webapps-deploy#335]
As per #154 - You should be able to specify the deployment folder in the YML file. 

The work around in #154 is not very acceptable considering any commit message is plain text and prone to error by any given developer. Also, given the fact that Azure Web Apps support multiple virtual folders, it makes sense the deployment script could to. 

~~In addition, extending that idea it would be nice to allow your own deployment script as Azure Deployments already does. If you have a depoy.cmd in your root folder it will over-ride the default. The same should be done here.~~

I suggest two new settings:
destination: <path>  ---> /api
~~build-script: <path>  ---> ./dist/deploy.cmd~~

Actually, the second point doesn't make sense unless you can pass VARs into the custom deployment command.

**Comment by John-Donalson** [comment]
This would be helpful, as the methods work but are not consistent. Destination URL of Zipdeploy in publish profile, and setting deployment target, restart, then deploy, the combination works, but still not a stable fix. Alternatively if you modify the repo name in an if statement of the deployment script, adds unnecessary steps and hard to scale this if working with  multiple services/repos.

**Comment by sgollapudi77** [comment]
Hi @NoCopy, since this ask is same as #340 we're closing this issue as duplicate and will track it in the other issue.
