### ISSUE TITLE
Package deployment using ZIP Deploy initiated.

### ISSUE THREAD

**Issue by RoelVerhees** [Azure/webapps-deploy#343]
Hi all, 

I know there are several other issue related to the problem and some of them are closed.
But the last couple of weeks we keep getting more and more issues with the deployment of Azure Functions with the help of Zip Deployment.

We are using an Azure Function with Python with a Linux Service Plan.

Sometimes, it works instantly but sometimes the deployment is just stuck at 
Package deployment using ZIP Deploy initiated.

This really needs to be fixed, imo

**Comment by sgollapudi77** [comment]
Hi @RoelVerhees , can you share more details like your app name or the deployment logs in which you're getting stuck and the time when you faced this issue?

**Comment by sgollapudi77** [comment]
Hi @RoelVerhees , if it is related to functions githubactions, can you please file it on this [repo](https://github.com/Azure/functions-action). Please feel free to re-open this issue with more details if the issue is related to the App-services github actions.
