### ISSUE TITLE
`images` is still required in the latest 2.2.10 release

### ISSUE THREAD

**Issue by nallenscott** [Azure/webapps-deploy#350]
Images was changed to not required in https://github.com/Azure/webapps-deploy/pull/302.

https://github.com/Azure/webapps-deploy/blob/fb8292eb575db1bb18a90627e8959cd51dbb355c/action.yml#L19-L21

**Comment by sgollapudi77** [comment]
Hi @nallenscott, since these changes are not released you're still seeing this error. We'll be doing a new release of `Azure/web-apps-deploy` action soon and update here.

**Comment by sgollapudi77** [comment]
Hi @nallenscott , we've released a new version of Github actions - v2.2.11. This issue should be resolved by now.
