### ISSUE TITLE
Deployment always failing with error "Failed to deploy web package to App Service"

### ISSUE THREAD

**Issue by nkomm00** [Azure/webapps-deploy#361]
Deployment always fails with error "**Failed to deploy web package to App Service**"
we have tried multiple times and there is no code change also, but still we are receiving the same error, also I have used the latest tag v2.2.11 but still we are seeing the same error when using this action, below is the error from a workflow run

**Stack: Node**
**Major version: Node 18**
** Minor Version: Node 18 LTS**

```
Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/95d775b1-xxx-4dad-xxxx-78f6acxxxxx.zip (146.88 MB) to /tmp/zipdeploy/extracted
Error: Failed to deploy web package to App Service.
Error: Deployment Failed, Package deployment using ZIP Deploy failed. Refer logs for more details.
```

**Comment by sgollapudi77** [comment]
Hi @nkomm00 , can you provide the appName so that we can look at what's happening internally?

**Comment by sgollapudi77** [comment]
Hi @nkomm00 , since there is already a similar issue, we'll track the issue on #362 . Closing this issue as duplicate, please feel free to check upon the parent issue.
