### ISSUE TITLE
Deprecation warning due to Node 16

### ISSUE THREAD

**Issue by Piedone** [Azure/webapps-deploy#372]
Node 16 is [now deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). Because of this, when using this action, you'll see warnings.

Please update the action to Node 20.

**Comment by surenderssm** [comment]
Thank you @Piedone for opening the issue, this is in our radar. Will keep the issue posted with progress,

**Comment by sgollapudi77** [comment]
[like]  Vamsi GollapuD reacted to your message:
________________________________

**Comment by Piedone** [comment]
Thank you!

**Comment by sgollapudi77** [comment]
Hi @Piedone ,  can you please paste the screenshots where you see this warning?

**Comment by Piedone** [comment]
![image](https://github.com/Azure/webapps-deploy/assets/1976647/2c40501e-fa05-425e-be31-3833f16874a5)

This is because this line: https://github.com/Azure/webapps-deploy/blob/e0d17a2aa934d0d1d4a1a2ee8013df2437122cd3/action.yml#L51

**Comment by sgollapudi77** [comment]
Thanks, @Piedone this helps. We'll look into this.

**Comment by nathanchase** [comment]
I'm not sure if your team is responsible on the Azure portal side for Node versioning, but it prevents us from using Node 20 there as well:
![image](https://github.com/Azure/webapps-deploy/assets/5963574/83f2b092-6eaf-4afb-bc34-0e6355473246)

**Comment by surenderssm** [comment]
@nathanchase - The LTS version of Node 20 was launched in October. We’re currently in the process of integrating Node 20 support into App Services. This feature is expected to roll out in the upcoming weeks. Stay tuned for further updates from us.

**Comment by surenderssm** [comment]
@nathanchase NODE 20-LTS is available on Linux App Service. In case you are using Windows App Service, it will be available in upcoming weeks. Thank you for your patience and feedback, appreciate it!

**Comment by nathanchase** [comment]
Thank you for the update!

**Comment by Piedone** [comment]
Any news here? After not showing them for a while, GitHub now shows the deprecation warning again.

**Comment by jsoref** [comment]
fwiw, #393 should resolve this

**Comment by Piedone** [comment]
[v3.0.1](https://github.com/Azure/webapps-deploy/tree/v3.0.1) addressed this.
