### ISSUE TITLE
Support for YAML/JSON formatted deploy credentials

### ISSUE THREAD

**Issue by frank-fischer-by** [Azure/webapps-deploy#45]
Hi,

so far I've had great success using this action together with https://github.com/Azure/login.
I like the idea of publish profiles for specific workflows, since they seem slightly less cumbersome and akin to SAS tokens.

I was slightly surprised, when I wanted to use the lazy approach and set up multiple CI pipelines for different WebApps:

```sh
az webapp deployment list-publishing-profiles \
  --query "[? publishMethod=='MSDeploy'] | [0]" \
  --resource-group "foo" \
  --name "bar"
```

produces

```json
{
  "SQLServerDBConnectionString": "",
  "controlPanelLink": "http://windows.azure.com",
  "databases": null,
  "destinationAppUrl": "http://<name>.azurewebsites.net",
  "hostingProviderForumLink": "",
  "msdeploySite": "<name>",
  "mySQLDBConnectionString": "",
  "profileName": "<name> - Web Deploy",
  "publishMethod": "MSDeploy",
  "publishUrl": "<name>.scm.azurewebsites.net:443",
  "userName": "$<name>",
  "userPWD": "<secret>",
  "webSystem": "WebSites"
}
```

---

https://github.com/Azure/webapps-deploy/blob/master/lib/Utilities/PublishProfile.js#L22
```typescript
new actions_secret_parser_1.SecretParser(publishProfileContent, actions_secret_parser_1.FormatType.XML);
```
🤔

> "Well it **does** make sense when looking at the [Publish Profile description](https://github.com/projectkudu/kudu/wiki/Deployment-credentials#site-credentials-aka-publish-profile-credentials) (where you describe the Portal approach).
> No biggie. They certainly have different output formats.

```sh
az webapp deployment list-publishing-profiles --help
```

> --output -o    : Output format.  Allowed values: `json`, `jsonc`, `none`, `table`, `tsv`, `yaml`, `yamlc`

🤦 

---

It's not a big thing to convert the JSON/YAML you retrieve via `azure-cli` to the XML as you would retrieve it via the portal. General support for either format (or both) supported by `azure-cli`would be greatly appreciated.
Or is it better to bring this up with the `azure-cli` team?

In any case, either solution would be welcome, because **service principals** can _only_ perform non-UI approaches, so the only way to retrieve the XML is not always possible 😞.

**Comment by N-Usha** [comment]
Thanks for reaching out @frank-fischer-by. Yes, this needs to be addressed by the Azure platform team, perhaps the Az CLI product team. We'll surely convey the feedback to the concerned team.

**Comment by frank-fischer-by** [comment]
Thanks for the feedback :). Looking forward to the outcome of this.

I _considered_ updating the action with support for JSON/YAML myself (I have barely any TypeScript experience; so no promise that I have the time to dig into how the deployment API works, how Typescript works and how GH actions fit into that).

Is this something that would be accepted or do you think it's more reasonable to wait for an answer from the Azure platform team first before investing work here.

**Comment by N-Usha** [comment]
Product team has confirmed that this issue is already getting tracked under azure-cli github repo - you can check the discussion & details on the GitHub issue. https://github.com/Azure/azure-cli/issues/13777.  Hoping that helps and Closing this issue for now. Thanks!
