### ISSUE TITLE
This job just started failing with Internal Server Error

### ISSUE THREAD

**Issue by RockManJoe64** [Azure/webapps-deploy#46]
Hi! I have been using this github action for months without issues. Unfortunately tonight I started seeing the following in my builds:
```
 Deploy to Azure WebApp1s
    NODE_VERSION: 12.x
Run azure/webapps-deploy@v2
  with:
    app-name: XXX
    publish-profile: ***
    package: .
    slot-name: production
  env:
    AZURE_WEBAPP_NAME: XXX
    AZURE_WEBAPP_PACKAGE_PATH: .
    NODE_VERSION: 12.x
##[error]Deployment Failed with Error: Error: Internal Server Error. Please try again
Error: [object Object]
```
The internal server error makes me think it's on Azure's end. But I am able to deploy my function app successfully from Visual Studio Code. Also, the object output at the end would be helpful if I knew how to `JSON.stringify` it! 😄 

Can you please advise?

**Comment by aksm-ms** [comment]
Issue is fixed in PR.

**Comment by GabrieleCastellani** [comment]
It is working again for me
