### ISSUE TITLE
Run from package deployment

### ISSUE THREAD

**Issue by alaatm** [Azure/webapps-deploy#5]
Is it possible to use [run from package](https://github.com/Azure/app-service-announcements/issues/84) deployment? This seems the default for [functions-action](https://github.com/Azure/functions-action) which takes care of these steps:
- Putting the zip in `home/data/SitePackages`
- Setting package name in `packagename.txt`
- Setting `WEBSITE_RUN_FROM_PACKAGE` to 1 in app settings

Also the [AzureWebApp@1](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureWebAppV1) task for Azure pipelines does same as above. However, webapps-deploy action just extracts the package into `wwwroot`.

**Comment by SumiranAgg** [comment]
You are right currently we have added auto-detect logic only which defaults to zip deploy. We can add provision similar to additional deployment techniques in the task.
@N-Usha Please look into it.

**Comment by k-miyake** [comment]
In my case, just setting `WEBSITE_RUN_FROM_PACKAGE = 1` in app settings enabled Run From Package.

**Comment by SumiranAgg** [comment]
Yeah thats the right way to go.
