### ISSUE TITLE
Webapp Deploy is acting weird

### ISSUE THREAD

**Issue by romil07** [Azure/webapps-deploy#51]
Webapp deploy action is succeeding for me but the webapp is not properly deployed.
My workflow can be seen [here](https://github.com/romil07/goSampleApp/blob/master/.github/workflows/deploytoContainerWebApp.yml) and the workflow run can be seen [here](https://github.com/romil07/goSampleApp/runs/893047470?check_suite_focus=true)

All is well till here. But when I go to my webapp, I get error. In the Diagnostic logs of the webapp, it says it couldn't authenticate while running the docker image pull. This is weird. It was able to do a docker push with the same credentials. Docker pull should also succeed.

I have already added my workflow run details above, if there are any other questions, please reach out to me directly.

**Comment by aksm-ms** [comment]
can you please paste the logs here?

**Comment by romil07** [comment]
My action run logs:
Updating App Service Configuration settings. Data: ***"linuxFxVersion":"DOCKER|rogoyalacrnew.azurecr.io/rogoyaltestwebapp-img:bf0a0a95bcf4a01c7ee3d5b7f2c7bda876880acb"***
##[debug][PATCH] https://management.azure.com/subscriptions/393a91ee-f98d-43ff-b964-009bda0fdf2e/resourceGroups/rogoyal/providers/Microsoft.Web/sites/rogoyal-test-webapp/config/web?api-version=2016-08-01
Updated App Service Configuration settings.
##[debug]making a restart request to app service
Restarting app service: rogoyal-test-webapp
##[debug][POST] https://management.azure.com/subscriptions/393a91ee-f98d-43ff-b964-009bda0fdf2e/resourceGroups/rogoyal/providers/Microsoft.Web/sites/rogoyal-test-webapp/restart?api-version=2016-08-01
Restarted app service: rogoyal-test-webapp
##[debug][POST] https://management.azure.com/subscriptions/393a91ee-f98d-43ff-b964-009bda0fdf2e/resourceGroups/rogoyal/providers/Microsoft.Web/sites/rogoyal-test-webapp/config/appsettings/list?api-version=2016-08-01
##[debug]Application Insights is not configured for the App Service. Skipping adding release annotation.
##[debug][PUT] ***rogoyal-test-webapp.scm.azurewebsites.net/api/deployments/bf0a0a95bcf4a01c7ee3d5b7f2c7bda876880acb1595314231008
##[debug]loaded affinity cookie ["ARRAffinity=f4813ea7d86ab3f78eee82b105d9493c485eef0aa9946886f824df9f199743f0;Path=/;HttpOnly;Domain=rogoyal-test-webapp.scm.azurewebsites.net"]
##[debug]updateDeployment. Data: ***"statusCode":200,"statusMessage":"OK","headers":***"transfer-encoding":"chunked","content-type":"application/json; charset=utf-8","server":"Kestrel","set-cookie":["ARRAffinity=f4813ea7d86ab3f78eee82b105d9493c485eef0aa9946886f824df9f199743f0;Path=/;HttpOnly;Domain=rogoyal-test-webapp.scm.azurewebsites.net"],"date":"Tue, 21 Jul 2020 06:50:35 GMT","connection":"close"***,"body":***"id":"bf0a0a95bcf4a01c7ee3d5b7f2c7bda876880acb1595314231008","status":4,"status_text":null,"author_email":null,"author":"romil07","deployer":"GitHub","message":"***\"type\":\"Deployment\",\"sha\":\"bf0a0a95bcf4a01c7ee3d5b7f2c7bda876880acb\",\"repoName\":\"romil07/goSampleApp\",\"slotName\":\"production\"***","progress":null,"received_time":"0001-01-01T00:00:00","start_time":"2020-07-21T06:50:33.9333248Z","end_time":"2020-07-21T06:50:33.9333248Z","last_success_end_time":null,"complete":false,"active":true,"is_temp":false,"is_readonly":false,"url":"https://rogoyal-test-webapp.scm.azurewebsites.net/api/deployments/bf0a0a95bcf4a01c7ee3d5b7f2c7bda876880acb1595314231008","log_url":"https://rogoyal-test-webapp.scm.azurewebsites.net/api/deployments/bf0a0a95bcf4a01c7ee3d5b7f2c7bda876880acb1595314231008/log","site_name":null***
Successfully updated deployment History at https://rogoyal-test-webapp.scm.azurewebsites.net/api/deployments/bf0a0a95bcf4a01c7ee3d5b7f2c7bda876880acb1595314231008
##[debug]Active DeploymentId :bf0a0a95bcf4a01c7ee3d5b7f2c7bda876880acb1595314231008
App Service Application URL: http://rogoyal-test-webapp.azurewebsites.net
::set-output name=webapp-url::http://rogoyal-test-webapp.azurewebsites.net
##[debug]='http://rogoyal-test-webapp.azurewebsites.net'
::set-env name=AZURE_HTTP_USER_AGENT::
##[debug]AZURE_HTTP_USER_AGENT=''
##[debug]Deployment Succeeded
##[debug]Node Action run completed with exit code 0
##[debug]Finishing: Run azure/webapps-deploy@v2

**Comment by aksm-ms** [comment]
@romil07 is this issue still occuring?

**Comment by romil07** [comment]
@aksm-ms No, this can be closed.
