### ISSUE TITLE
Running subsequent jobs only after the deployment triggered by the webapps-deploy action completes

### ISSUE THREAD

**Issue by rukasakurai** [Azure/webapps-deploy#64]
I would like to automate the deployment of code to Azure Web App for Containers using GitHub Actions.

The approach that I am taking includes the following steps:
1. CI, etc.
2. Deploy to a staging slot in App Service using Azure/webapps-deploy@v2
3. Validate the deployment in the staging environment (e.g., GET to one of the APIs that is deployed)
4. Swap staging and production slots on the App Service
5. Check the production endpoint etc.

However, I have noticed that the job to validate the deployment to the staging slot (step#3) runs before the staging slot is actually updated with the new code, which is not what is intended.

One potential approach might be to wait a certain amount of time before moving on to step#3, but this would only increase the likelihood that the deployment to staging is done, rather than guaranteeing it. And adding a long wait would unnecessarily increase the lead time until the deployment is done.

Another approach could be to check the version number deployed on the staging slot before moving on to step#3. However, I'm wondering if there is a simpler way (e.g., adding a line or two to the GitHub Action workflow yaml code to check for this).

Could someone provide advice please?

**Comment by JasonFreeberg** [comment]
@N-Usha -- We are introducing a new API that returns the status of a user's code deployment ("deployment received", "in-progress", "completed", "failed", etc.). Integrating the webapps-deploy action to ping this new API would fulfill this customer's request. The API is deploying now to testing regions, and I can share some notes next week.

CC @AmrutaKawade

**Comment by aksm-ms** [comment]
Marking this as enhancement. cc: @N-Usha

**Comment by vinicius-batista** [comment]
Is there any update on this? I'm trying to build a similar workflow described and facing the same issue. In practice, when I run swap, my application goes to old version deployed to staging slot, while I expected to swap after staging slot has the new deployed version.
