### ISSUE TITLE
Backups are only functionnal using StorageV2

### ISSUE THREAD

**Issue by svallier** [Azure/webapps-deploy#66]
It's allowed to set a backup scheduling using ARM template or powershell. 
Otherwise, backups fail

it seems that backups are only functionnal using StorageV2. but it's not specified in requirements :
https://docs.microsoft.com/en-us/azure/app-service/manage-backup#requirements-and-restrictions

**Comment by svallier** [comment]
.

**Comment by svallier** [comment]
See #67

**Comment by aksm-ms** [comment]
@N-Usha Can you please take a look at this and let me know if we can add this as an enhancement?

**Comment by N-Usha** [comment]
This looks to be a product limitation that an issue with the action. @JasonFreeberg / @ehamai - Is this something you could help respond?

**Comment by JasonFreeberg** [comment]
Hi @N-Usha, I copied @svallier's issue to the Docs repo: https://github.com/MicrosoftDocs/azure-docs/issues/66898

I'll send an email now to Cephas and Gaurav. They should be able to address this. I think we can close this issue and use the new Docs issue to track it now.
