### ISSUE TITLE
WebApp can't be backuped into Storage Accounts with Premium LRS Sku

### ISSUE THREAD

**Issue by svallier** [Azure/webapps-deploy#67]
It's allowed to schedule an Azure WebApp using ARM Template or powershell specifying all existing Storage Account Sku's
But backups fails where the storage Account has Sku "Premium LRS".

When i get the request that filtering storage accounts from WebApp backup selection in portal, i can see that the filter "Premium LRS" is applied. 

where type in~ ('microsoft.storage/storageaccounts','microsoft.classicstorage/storageaccounts')| extend isClassic = (type =~ 'microsoft.classicstorage/storageaccounts')| extend isHnsEnabled = coalesce(properties.isHnsEnabled, false)| extend allowSharedKeyAccess = coalesce(properties.allowSharedKeyAccess, true)| extend skuName = replace('-', '_', tostring(iff(isClassic, properties.accountType, sku.name)))| project id, name, location, skuName, kind, isHnsEnabled, allowSharedKeyAccess| summarize name = any(name), location = any(location), skuName = any(skuName), ['kind'] = any(kind), isHnsEnabled = any(isHnsEnabled), allowSharedKeyAccess = any(allowSharedKeyAccess) by id| order by name asc **| where skuName !in~ ('Premium_LRS')"**

Otherwise there is no information about this requirement in documentation :
https://docs.microsoft.com/en-us/azure/app-service/manage-backup#requirements-and-restrictions

If this requirement is "Normal", it should be impossible to schedule backups using Storage Accounts with "Premium LRS" Sku through ARM template or Edit-AzWebAppBackupConfiguration cmdlet and the documentation should be indicate this requirement

**Comment by aksm-ms** [comment]
@svallier are you facing any issue with webapps-deploy github action? This repo tracks issues regarding the azure/webapps-deploy action.

**Comment by aksm-ms** [comment]
@svallier are you still facing the issue?

**Comment by aksm-ms** [comment]
Closing the issue. Please feel free to reopen for any further queries.

**Comment by svallier** [comment]
i do not use github actions. I deploy the template through azure DevOps (but t should be the same issue in Github Actions. 'cause it's not caused by the DevOps platform). 

You are not able to backup WebApp into Premium LRS Storage Account 

the problem is  **there is nothing avoiding de scheduling of this backup using the ARM template or the cmdlet "Edit-AzWebAppBackupConfiguration**". The scheduling is successful even the storage Accounts is "Premium LRS Sku" . But the backups fail then
