### ISSUE TITLE
Deploy to Azure App Service fails with "Encountered a retriable status code: 409. Message: 'Conflict'"

### ISSUE THREAD

**Issue by rriski** [Azure/webapps-deploy#7]
Using github actions with azure/webapps-deploy@v1 fails with a 409 response. Sometimes, seemingly randomly, the deploy goes through. In addition, the annotations display [object Object] as the error. Rerunning the action sometimes resolves the issue, sometimes not.

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/25483483/70918824-672cee80-2028-11ea-9218-46e951769c88.png">

**Comment by eaarora-ms** [comment]
@rriski Sorry for the delay in reply. The message mostly occurs when there are simultaneous operations or deployments happening on the app service. Can you please confirm if the issue still persists and if you are doing any parallel deployments? Thanks.

**Comment by eaarora-ms** [comment]
CLosing due to no response. Please comment to re-open.
