### ISSUE TITLE
set-env is deprecated and throwing warnings in workflows

### ISSUE THREAD

**Issue by timheuer** [Azure/webapps-deploy#70]
My workflow is now showing me warnings regarding the deprecation of `set-env` https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/. Need to upgrade to latest core toolkit

**Comment by rtheil** [comment]
Same issue, using webapps-deploy@v2

**Comment by AmrutaKawade** [comment]
PR is merged. you can use v2 tag
