### ISSUE TITLE
There is not enough space on the disk.\r\n

### ISSUE THREAD

**Issue by CodeWarrior-Hawaii** [Azure/webapps-deploy#75]
Deploying fairly small (3x components) angular app to Azure App Service.  Web App built and deployment attempted but resulted in `There is not enough space on the disk.\r\n`.

    Package deployment using ZIP Deploy initiated.
    Fetching changes.
    Cleaning up temp folders from previous zip deployments and extracting pushed zip file C:\local\Temp\zipdeploy\ad1141rx.zip (152.54 MB) to C:\local\Temp\zipdeploy\extracted
    There is not enough space on the disk.\r\n
    Error: Failed to deploy web package to App Service.
    Error: Deployment Failed with Error: Package deployment using ZIP Deploy failed. Refer logs for more details.

**Comment by aksm-ms** [comment]
@CodeWarrior-Hawaii Can you please share your workflow and detailed output logs?

**Comment by aksm-ms** [comment]
Closing due to not enough info to debug. Please feel free to reopen the issue if needed.
