### ISSUE TITLE
Error: EAI_AGAIN Error: Deployment Failed with Error: Error: Failed to get app runtime OS

### ISSUE THREAD

**Issue by nareshbulusu** [Azure/webapps-deploy#78]
Getting the below error. Any help is appreciated, Thanks!

![image](https://user-images.githubusercontent.com/13373929/97606682-12267b00-1a36-11eb-9e60-aaeabc8cea9e.png)

The configuration I am using is below.

    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '*******************/****:**'

**Comment by nareshbulusu** [comment]
Turns out, this was because of the preceding "https://" I have incorrectly added to the publishurl of Web Deploy profile. I have removed "https://" it so it is just "exampleapp.scm.azurewebsites.net:443" and issue got resolved.

**Comment by dtmzr** [comment]
@nareshbulusu currently facing the same error message but my deployment profile seems correct.

Thats what my workflow outputs as configuration:
```yml
with:
    app-name: [app-name]
    publish-profile: ***
    images: [image-name]
    slot-name: production
    package: .
```

Where only `app-name`, `publish-profile` and `images` are set by me.

Did you adjust anything else? I assume something with the authentication or authorization is going wrong but the error message leads me nowhere.

I also had adjusted my `WEBSITE_WEBDEPLOY_USE_SCM` variable (as described here https://github.com/Azure/webapps-deploy/issues/28#issuecomment-720182421) on the instance before pulling the publish profile.

**Comment by Duchynko** [comment]
My deployments started failing today out of nowhere. I'm getting the same error.
`Error: Deployment Failed with Error: Error: Failed to get app runtime OS`

**Comment by riteshbxr** [comment]
The issue in my case was resolved by resetting the publish profile and updating github action with the new one
