### ISSUE TITLE
Missing PHP runtime

### ISSUE THREAD

**Issue by jjindrich** [Azure/webapps-deploy#81]
There is missing PHP runtime for WebApp deployment

**Comment by aksm-ms** [comment]
@jjindrich Can you please provide more description of the issue?
Also are you facing any issue with webapps/deploy@v2 action? If so, please share workflow used along with detailed logs.

**Comment by jjindrich** [comment]
Action webapps/deploy@v2 not allows deployment to Azure Web App with PHP runtime. Check this https://docs.microsoft.com/en-us/azure/app-service/quickstart-php?pivots=platform-linux

**Comment by aksm-ms** [comment]
@jjindrich I am able to deploy to PHP app using azure/webapps-deploy@v2. I have updated documentation with a sample workflow for PHP. @N-Usha Please review the documentation PR.

**Comment by aksm-ms** [comment]
@jjindrich Please let me know if you are facing any other issues.

**Comment by jjindrich** [comment]
Hi, thanks for update @aksm-ms. I tried to use. I updated yml and created new secret AZURE_WEBAPP_PUBLISH_PROFILE. I copied content of Get publish profile from Web App blade (following https://github.com/Azure/actions-workflow-samples/blob/master/assets/create-secrets-for-GitHub-workflows.md#set-secret-with-web-app-publish_profile).

But getting this errors:
Error: Failed to fetch credentials from Publish Profile. For more details on how to set publish profile credentials refer https://aka.ms/create-secrets-for-GitHub-workflows
Error: Deployment Failed with Error: Error: Publish profile does not contain kudu URL

It seems that workflow cannot see secret I created. My workflow https://github.com/jjindrich/jjazure-web-php/blob/master/.github/workflows/jjwebphpsymphony-cicd.yml

**Comment by aksm-ms** [comment]
@jjjndrich While using publish profile credentials for app services created on linux, please follow the following steps:
1. configure an application setting "WEBSITE_WEBDEPLOY_USE_SCM" and set it to true.
2. After setting the value, download publish profile from portal.
3. Use the same in your workflow.

Please refer this [https://github.com/azure/webapps-deploy#configure-deployment-credentials](https://github.com/azure/webapps-deploy#configure-deployment-credentials)

**Comment by jjindrich** [comment]
I can confirm, it works. Thanks for help.
