### ISSUE TITLE
##***error***Deployment Failed with Error: Error: Action does not support app service with kind app,migration.

### ISSUE THREAD

**Issue by jaspecla** [Azure/webapps-deploy#88]
I created a new App Service using the Azure App Service Migration assistant.  The migration assistant creates app services with the "kind" attribute set to "app,migration" as opposed to "app."

This causes the action to fail with the error in the title:

##***error***Deployment Failed with Error: Error: Action does not support app service with kind app,migration.

This may be related to issue #83

**Comment by aksm-ms** [comment]
@N-Usha Currently we do not support app kind "app,migration" in our action code. Can we add this as a future enhancement?

**Comment by aksm-ms** [comment]
As discussed with @N-Usha, marking this as an enhancement.
