### ISSUE TITLE
webapp-url output is a non-SSL URL provided

### ISSUE THREAD

**Issue by timheuer** [Azure/webapps-deploy#96]
For some reason the `applicationURL` value in this action is getting a non-SSL based URI which then gets passed along to other areas like the output of `webapp-url` which can be used in later actions.  

https://github.com/Azure/webapps-deploy/blob/c6cf55c3ba862aca5fe5a39958d0191a5f396bd1/src/DeploymentProvider/Providers/BaseWebAppDeploymentProvider.ts#L57

This should be changed to have the SSL-based URI by default.

It appears to be coming from: 
https://github.com/microsoft/pipelines-appservice-lib/blob/714433932820111567046bd53f47e9131d95930a/src/RestUtilities/AzureAppServiceUtility.ts#L39

Which is in the publish profile.  Indeed the pubprofile destinationAppUrl is a non-secure URL for some reason when downloading the publish profiles...this should be changed.  Other places in the publish profile are 443/SSL based except this one.

**Comment by arjgupta** [comment]
@timheuer to get publish profile to use https, you will need to go to the TLS/SSL settings of your app and set it to be 'HTTPS only'. After making this change, the publish profile will use https instead of http. you can download the publish profile and verify it.
