### ISSUE TITLE
Deploying to Azure App Service fails with "Deployment Failed with Error: Error: Failed to deploy web package to App Service.Conflict (CODE: 409)"

### ISSUE THREAD

**Issue by ikuosaito1989** [Azure/webapps-deploy#98]
I have the same problem with GitHub Actions as with the issue.

https://github.com/Azure/webapps-deploy/issues/7 

It may succeed if executed repeatedly.
I am using a B1 instance of App Service on Linux, and I am attaching the yaml of GitHub Actions and the error log. 

Please let me know the solution🙏
<img width="733" alt="スクリーンショット 2020-12-26 14 52 13" src="https://user-images.githubusercontent.com/48668579/103146349-4050de80-478b-11eb-938d-f4ef9daf760b.png">
<img width="267" alt="スクリーンショット 2020-12-26 14 52 28" src="https://user-images.githubusercontent.com/48668579/103146350-434bcf00-478b-11eb-8fdf-a1e676cc0bad.png">

**Comment by AmrutaKawade** [comment]
We use kudu APIs internally for deployment. there seems to be open issue on Kudu for similar thing.
Can you try scaling up your app service plan as mentioned here https://github.com/projectkudu/kudu/issues/3042#issuecomment-665659432.

**Comment by ikuosaito1989** [comment]
@AmrutaKawade 
Thanks for the reply!
I'll post the service plan on Kudu's issue 💪.

**Comment by ikuosaito1989** [comment]
@AmrutaKawade 
Thanks for the answer!

I'll ask my question over at kudu!
